### ISSUE TITLE
(BUG) ST devices with placeholder type will break Homebridge connectivity

### ISSUE THREAD

**Issue by badamonis** [tonesto7/homebridge-smartthings-v2#10]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The SmartApp and Device Handler are using the latest code available.
-  [x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 1
-  Mobile App Version(Not required):
-  SmartApp Version: 2.0.1
-  Device Handler Version: N/A
-  Homebridge Version: 2.0.1
-  NodeJS Version: 10.17.0

## Expected Behavior
**Tell us what you think should be happening**
When adding a device under the Light category, it should add to Homebridge/Home iOS app

## Current Behavior
**What happens instead of the expected behavior?**
When a device is added that has a type of placeholder (I have Kasa/TP-Link and Meross devices added to ST which default to this), Homebridge will no longer update the Home app and all devices will eventually become unresponsive until that placeholder device is removed.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Add a device via the Homebridge v2 SmartApp with a type of placeholder (shows in IDE type column)
2. Restart Homebridge
3. View Home iOS app and the device will not show up
4. If you try to remove Home from iOS app and re-add accessory, it will be unable to connect to Homebridge.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**
I have several WiFi devices added to ST that I'd like to control with Homebridge and they aren't added. I can work around this by editing the device type in the IDE to something else like Light Capability.

---
Please include a copy of any relevant log output to assist in tracking down the bug
There are no visible errors when this occurs, even with debug mode enabled.

**Comment by tonesto7** [comment]
I will try to duplicate but I have many devices that are placeholders under homebridge.  How many devices are you importing into homebridge

**Comment by badamonis** [comment]
Upon further review, looks like this may be related to devices without a device network ID. Just so happened that all of the placeholders I have do not have a device network ID populated. This is a required field in the IDE but ST looks like it will allow certain devices to be created without one

This can be replicated with just 1 device.

**Comment by tonesto7** [comment]
@badamonis The missing device id should have no effect on homebridge.  I only use the GUID .id ST assigns to each device to identify it in ST.

**Comment by tonesto7** [comment]
What happens if you add them to the light capability input in the homebridge smartapp?

**Comment by badamonis** [comment]
@tonesto7 If I try to add a device without an 'Device Network Id', I can see the device being registered by your plugin, however, all of my devices in the Home app go unresponsive and that device will not show up. If I remove that device, it will go back to normal. If I add something into 'Device Network Id' field in the IDE, and readd it in the SmartApp, it will sync with the Home app. Looking at the settings, the 'Device Network Id' shows up in the 'Serial Number' field in the Home app.

It does not matter what category I add it to in the SmartApp. Behavior is the same.
