### ISSUE TITLE
Accessories added and work in HB but not added in Home

### ISSUE THREAD

**Issue by kwalkington** [tonesto7/homebridge-smartthings-v2#121]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The SmartApp and Device Handler are using the latest code available.
-  [ x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 104
-  Mobile App Version(Not required):
-  SmartApp Version:2.3.2
-  Device Handler Version: plugin 2.3.2
-  Homebridge Version: hoobs 3.1.22 running 0.4.50
-  NodeJS Version: 12.13.1

## Expected Behavior
after setting up smartapp in smartthings IDE, app in ios smartthings classic app, and pluggin in hoobs, the 104 accessories would be added to HB and then visible in home

## Current Behavior
devices controllable in hoobs via pc browser, but do not present in home.  Was previously working with less accessories

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.  install smartapp on IDE
2.  use classic ios app to setup accessories, some selected as lights and fans, and other
3. install plugin via hoobs and enter config settings
4. reboot homebridge

## Context
**How has this issue affected you? What are you trying to accomplish?
My smarthome functionality is totally lost if I cannot relate non smartthings devices to smartthings

---
log shows all the accessories added to homebridge, no apparent errors, just one line I don't understand:
[Homebridge] NOTICE: Unknown Capabilities: ["Relay Switch"]

**Comment by kwalkington** [comment]
when restarting homebridge service, homebridge thinks the accesories are already in home, and has them selected to update vs add...

[Homebridge] NOTICE: Temperature Unit is Now: (F)
[Homebridge] NOTICE: Updating Global Values | HubIP: 192.168.1.95 | UseLocal: false
[Homebridge] WARN: Devices to Remove: (0) []
[Homebridge] INFO: Devices to Update: (105)
[Homebridge] GOOD: Devices to Create: (0) []
[Homebridge] ALERT: Total Initialization Time: (4 seconds)
[Homebridge] NOTICE: Unknown Capabilities: ["Relay Switch"]
[Homebridge] INFO: SmartThings DeviceCache Size: (105)
[Homebridge] INFO: WebServer Initiated...
[Homebridge] INFO: Sending StartDirect Request to SmartThings | SendToLocalHub: (false)
[Homebridge] INFO: Direct Connect Active | Listening at 192.168.1.224:8000

**Comment by kwalkington** [comment]
I got more devices to show up in Add vs Update, but they still don't appear in home

**Comment by kwalkington** [comment]
Is there a maximum of 149 accessories with this plugin?

**Comment by tonesto7** [comment]
If they aren't being created clear the homebridge cachedAccessories folder.

Each homebridge instance has a limit of 149 accessories. 
So if you have multiple plugins that import over 149 accessories than it will cause the plugin to crash.
