### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by nathan-wagner** [tonesto7/homebridge-smartthings-v2#122]
I’m having trouble with some virtual switches. Is PubNub still supported for updates to homebridge with the “update_method” line in the configuration.json?  If so, any howto’s on how to set that up so that isn’t using direct polling?  Thanks.

**Comment by tonesto7** [comment]
Pubnub is not supported anymore because it's not required.  
Polling no longer occurs either.  ST events are sent directly to the homebridge plugin resulting in realtime updates under homekit
