### ISSUE TITLE
(BUG) Device from Smartthings does not exist in Smartthings

### ISSUE THREAD

**Issue by hakansjoo** [tonesto7/homebridge-smartthings-v2#125]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The SmartApp and Device Handler are using the latest code available.
-  [X] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Really just one, and HomeBridge and HomeKit. It's not terrible, just annoying. 
-  Mobile App Version(Not required): SmartThings 1.6.45-374
-  SmartApp Version: not sure what this is?
-  Device Handler Version: there isn't one!
-  Homebridge Version: 0.4.53
-  NodeJS Version: v13.11.0 (although Config UI X claims it's v12.16.1)

## Expected Behavior
I don't expect to see a device in HomeBridge that doesn't exist in Smartthings.

## Current Behavior
A Security System that does not belong to me is showing up in HomeBridge (with a reference to Smartthings).

## Steps to Reproduce (for bugs)
Live where I live, install a Smartthings 3rd gen hub, connected it HomeBridge using homebridge-smartthings-v2 and watch.

1. I had a SmartThings (GP-U9995SJVLGDA 3rd gen, firmware 000.029.00008) installed a couple of moths ago but gave up on it because it showed a device (a Security System) in HomeBridge and HomeKit that doesn't belong to me. I just decided to give it another shot. Exact same issue: the minute I got the SmartThings Hub up and running and connected to HomeBridge, a Security System (with virtually no information) in HomeBridge/HomeKit showed up that simply doesn't exist in SmartThings (or I'm not that smart, which is a distinct possibility). However, it's clear from HomeBridge and HomeKit that it originates from Smartthings. 

## Context
It doesn't affect me much, it's a tad annoying but I don't think I should have full access to someone else's security system!

Please see the (little) information I have from HomeBridge, HomeKit and Smartthings. Any thought or idea on how to proceed is appreciated. I'm sure the answer is staring right at me but... I'm stuck...

Thanks!

![Alarm](https://user-images.githubusercontent.com/60196587/78944814-c6f24e00-7a8c-11ea-9586-4a03ecefe167.jpg)

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
This is created because you must have SmartHomeMonitor installed under ST... It allows arming/disarming of SHM
