### ISSUE TITLE
Ge Motion Switch 26931 supported?

### ISSUE THREAD

**Issue by skazzyskills** [tonesto7/homebridge-smartthings-v2#126]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The SmartApp and Device Handler are using the latest code available.
-  [x ] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 4
-  Mobile App Version(Not required):
-  SmartApp Version: v2.32
-  Device Handler Version: 
-  Homebridge Version:0.4.53
-  NodeJS Version:

## Expected Behavior
**Tell us what you think should be happening**
Everything is working;however, the Ge Motion Switch 26931 (4 of them) say 'not supported'. Have I done something wrong? They work fine in SmartThings, and I just wanted the on/off ability for these switches. No dimmer, etc.
## Current Behavior
**What happens instead of the expected behavior?**
It says 'unsupported' for the switches.
## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Everything is installed, but in 'accessories' the 4 switches say 'unsupported'.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
To be able to see my switches and turn them on/off in Homekit.
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
I see no reason why it wouldn't work.  As long as it contains the switch capability it will function as a switch.

Because motion and switch on the same device are rare it may be ignoring the switch capability and using motion.  Try using the filter options in the smart app to filter out the motion capability and see if they show as switches.

**Comment by skazzyskills** [comment]
I filtered out the motion but still see unsupported. :-(

**Comment by skazzyskills** [comment]
Ok..I figured it out..I used another device handler GE Z-Wave Motion Sensor Switch (Model 26933) and I was able to get a light switch. Thanks!
