### ISSUE TITLE
(BUG) {Plugin not working after updating Hoobs to 3.1.27} 

### ISSUE THREAD

**Issue by adavison007** [tonesto7/homebridge-smartthings-v2#130]
@tonesto7  I'm running your latest version and have just updated hoobs to their latest version, all other plugins work, but it has stopped SmartThings from working, see logs

<img width="1281" alt="Screenshot 2020-04-19 at 11 10 25" src="https://user-images.githubusercontent.com/47482260/79685185-95b51300-822e-11ea-8355-8dbb7c09edf6.png">

**Comment by tonesto7** [comment]
@adavison007 There is nothing wrong with the plugin under Hoobs.  I've experienced similar issues with other plugins after a recent update.

Try the HOOBS support

**Comment by adavison007** [comment]
@tonesto7 thanks, I’ve spoken to support, had to delete and reinstall and all working again 😮
