### ISSUE TITLE
(BUG) Homebridge won't launch; Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory 

### ISSUE THREAD

**Issue by BrennonTWilliams** [tonesto7/homebridge-smartthings-v2#142]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The SmartApp and Device Handler are using the latest code available.
-  [ x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 0
-  Mobile App Version(Not required): Latest
-  SmartApp Version: Homebridge V2 version 2.3.2; plugin v2.3.3
-  Device Handler Version: Latest
-  Homebridge Version: Hoobs 3.1.23; Homebridge 0.4.50
-  NodeJS Version: 12.14.1

## Expected Behavior
Homebridge should launch, all devices should be detected.

## Current Behavior
After adding the [Sylvania RGB LED Lightstrip](https://www.amazon.com/dp/B00R1PB80I/) in the HomeKit app within SmartThings, Homebridge throws an error and won't launch. The lightstrip is classified as a light along with the other lights I have in SmartThings.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Pair Lightstrip
2. Homebridge V2 app within SmartThings: Define Device Types -> Lights -> Check "Slyvania Light" and hit done -> Next -> Done
3. Start Homebridge

## Context
Lightstrip is new from Amazon, planning on buying several more if it works.
---
## Log

```
[Homebridge] [5/5/2020, 7:50:55 PM] [SmartThings-v2] Initializing SmartThings-v2 platform...
[Homebridge] INFO: Homebridge Version: 2.4
[Homebridge] INFO: SmartThings-v2 Plugin Version: 2.3.3
[Homebridge] INFO: Checking Package Version for Updates...
[Homebridge] [5/5/2020, 7:50:56 PM] Loading 0 accessories...
[Homebridge] [5/5/2020, 7:50:56 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 99375d65-2066-4c41-97d4-d762221429a1
    at Bridge.Accessory.addBridgedAccessory (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)
    at Server._configCachedPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:360:22)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:82:10)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[Homebridge] ERROR: uncaughtException: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 99375d65-2066-4c41-97d4-d762221429a1
[Homebridge] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 99375d65-2066-4c41-97d4-d762221429a1
[Homebridge] at Bridge.Accessory.addBridgedAccessory (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)
[Homebridge] at Server._configCachedPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:360:22)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:82:10)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:955:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:811:32)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:723:14)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[Homebridge] [5/5/2020, 7:50:56 PM] Got SIGTERM, shutting down service...
```

**Comment by tonesto7** [comment]
This is not something I can help with...  Some of the devices being used must have the same device id.

**Comment by adam8810** [comment]
I was having this problem and realized I was having multiple accessories with the same name coming back from the Smarthings REST API plugin. After investigating I found out that some of my accessories were listed in multiple categories so I removed them from one and it no longer had issues starting. Hope this helps someone

**Comment by tonesto7** [comment]
The smartapp should have pointed it out to you.

**Comment by designorant** [comment]
This may also happen due to an accessory being cached twice in Homebridge, check for duplicates at:
**Homebridge Settings → Manage Cached Accessories → Remove Single Cached Accessory**
