### ISSUE TITLE
[ISSUE] We received a request from a client that didn't provide a valid access_token and app_id Error

### ISSUE THREAD

**Issue by kwalkington** [tonesto7/homebridge-smartthings-v2#15]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X ] The SmartApp and Device Handler are using the latest code available.
-  [X ] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: NONE
-  Mobile App Version(Not required):
-  SmartApp Version: 2.02
-  Device Handler Version:
-  Homebridge Version: 3.1.1
-  NodeJS Version:

## Expected Behavior
AFTER CONFIG ADDED FROM THE COPIED CODE IN SMARTAPP, HOMEBRIDGE WOULD START AT LEAST AFTER RESTART.

## Current Behavior
**What happens instead of the expected behavior?**  HOMEKIT DOESN'T GET NEW DEVICES.  HOMEBRIDGE SHOWS THE NEW DEVICES BUT ERRORS IN LOG.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.  GETHUB INTEGRATION INSTALL PER INSTRUCTIONS
2. SMARTAPP INSTALL. SELECTED 9 SWITCHES, SHM MODES
3. INSTALL PLUGIN VIA HOOBS 3.1.1
4. COPY TEXT FROM APP AND PAST OVER THE EXISTING CONFIG ADDED ALREADY BY INSTALL.

## Context
**How has this issue affected you? What are you trying to accomplish?  WANT SMARTTHINGS HOMEBRIDGE INTEGRATION
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug
Unable to determine plugin type for "homebridge-smartthings-v2"
[Homebridge] [12/14/2019, 22:12:21][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:21][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:21][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:22][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:22][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:22][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:22][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:22][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:23][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:23][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:23][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:23][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:23][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:23][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:23][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:23][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:24][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[Homebridge] [12/14/2019, 22:12:24][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id

**Comment by kwalkington** [comment]
*homebridge does start, errors in log

**Comment by kwalkington** [comment]
The smartthings devices are now showing in Homebridge and Home but the homebridge logs are still giving this error:
[Homebridge] [12/15/2019, 10:50:24][SmartThings-v2]ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id

**Comment by tonesto7** [comment]
This error occurs when the SmartApp app_id and access_token and the app_id and access_token in the config.json file do not match.

**Comment by kwalkington** [comment]
But I verified that they both match.

**Comment by kwalkington** [comment]
I have not changed anything in my setup, but the hoobs3/homebridge log is no longer giving that error.  Is it possible that it takes a matter of hours for something to be processed?

**Comment by tonesto7** [comment]
@kwalkington no it should be instant I will look at removing the check for the Id and token

**Comment by tonesto7** [comment]
This should be resolved in the recent release... Please update the smartapp and plugin
