### ISSUE TITLE
(BUG) Admin page blank on mobile devices

### ISSUE THREAD

**Issue by BrennonTWilliams** [tonesto7/homebridge-smartthings-v2#156]
-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The SmartApp and Device Handler are using the latest code available.
-  [ x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 5
-  Mobile App Version(Not required):
-  SmartApp Version: latest
-  Device Handler Version: latest
-  Homebridge Version: 3.2.6
-  NodeJS Version: 12.14.1

## Expected Behavior
Entering the IP address for the HOOBS admin panel should show the page when accessed from an iPad or other mobile device that is connected to the same wifi network.

## Current Behavior
Entering the IP for the HOOBS console leads to a blank page. It works fine on my  laptop and desktop, but not on any mobile devices.
I tried the ```rm desktop.json``` command per another issue and it had no effect.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Enter IP address for HOOBS console on a mobile device connected to the same wifi network. 
2. Blank page returns.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**
I have two wall mounted  iPads to use the console, but cannot access it.
---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
I believe this issue needs to be opened up under the Hoobs github
