### ISSUE TITLE
Love to see ring doorbell, security cameras in Google home,

### ISSUE THREAD

**Issue by treforparr** [tonesto7/homebridge-smartthings-v2#159]
I was thinking could you smart things to linking with Google home and maybe bring in  anyway to interlink the Google home from Smath things with ring doorbell

**Comment by treforparr** [comment]
I would love to see smart things and ring doorbell integrated and integrated into HomeBridge

**Comment by jdebardi** [comment]
Ring has an official Smarthings integration already (just add device in the app) and there is a homebridge-ring plugin as well. I use both. https://www.npmjs.com/package/homebridge-ring

I think the ring devices are probably too varied/complicated to allow for easy compatibility in the homebridge-SmartThings plugin IMO, hence I use direct for both.
