### ISSUE TITLE
[ISSUE] HOOBS Plugin Configuration Page Blank

### ISSUE THREAD

**Issue by bloody193** [tonesto7/homebridge-smartthings-v2#16]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ X] The SmartApp and Device Handler are using the latest code available.
-  [ X] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 0
-  Mobile App Version(Not required):
-  SmartApp Version: v1.6.1
-  Device Handler Version:
-  Homebridge Version: Hoobs 3.0
-  NodeJS Version: v12.13.1

## Expected Behavior
**Tell us what you think should be happening**
I should be able to see my devices I linked to the plugin in my home kit.

## Current Behavior
**What happens instead of the expected behavior?**
When plug in is added into Hoobs you no longer get the quick edit config like you did on the previous version of tonesto7 smarthings plug in and No devices are displayed. 

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug
Unable to determine plugin type for "homebridge-smartthings-v2"
Unable to determine plugin type for "homebridge-smartthings-v2"

**Comment by tonesto7** [comment]
Something wasn't installed correctly, because the quick config is included and working along with the plugin.  You can not directly update an existing version of the plugin.  You must remove the previous version from HomeKit and clear the persist and accessories folder located where the config.json is.

**Comment by bloody193** [comment]
All this has been done, does it make a difference that i'm not working with home bridge but im using hoobs3.0?

**Comment by bloody193** [comment]
I just added homebridge-smartthings-v2 on to a fresh copy of "hoobs 3.0" running on a virtual machine and I can confirm this fixed the "Unable to determine plugin type for "homebridge-smartthings-v2" but the quick config still does not show.

**Comment by tonesto7** [comment]
I haven't used hoobs before but if I have time will try it out.

**Comment by kwalkington** [comment]
FYI. I use hoobs and when I installed STHBv2 it placed a few lines as a placeholder for the platform in the config automatically. Although to see it you have to go into the whole config file in advanced as compared to just seeing the applicable code which is a new function in hoobs 3, vs 2. Then I just copied and paste the code from the smartapp into the config.

**Comment by bloody193** [comment]
> FYI. I use hoobs and when I installed STHBv2 it placed a few lines as a placeholder for the platform in the config automatically. Although to see it you have to go into the whole config file in advanced as compared to just seeing the applicable code which is a new function in hoobs 3, vs 2. Then I just copied and paste the code from the smartapp into the config.
> […](#)
> On Dec 15, 2019, at 10:38 PM, Tonesto7 ***@***.***> wrote: ﻿ I haven't used hoobs before but if I have time will try it out. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks I took your advice and added the info into the config under advance and im able to add my devices but then I get these errors and do not get real time status on the devices. 

[Homebridge] (node:851) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
[Homebridge] [12/16/2019, 20:03:35][SmartThings]NOTICE: setting temperature_unit to (F)
[Homebridge] [12/16/2019, 20:03:35][SmartThings]NOTICE: Updating Global Values | HubIP: 10.0.0.32 | UseLocal: false
[Homebridge] [12/16/2019, 20:03:35][SmartThings]WARN: Devices to Remove: (0)
[Homebridge] [12/16/2019, 20:03:36][SmartThings]INFO: Devices to Update: (0)
[Homebridge] [12/16/2019, 20:03:36][SmartThings]GOOD: Devices to Create: (2)
[Homebridge] [12/16/2019, 20:03:36][SmartThings]INFO: Added Device: (Garage Entry Door | 3bb1cf9b-bbe1-4907-8025-a2166efa818d)
[Homebridge] [12/16/2019, 20:03:36][SmartThings]INFO: Added Device: (Security Alarm | alarmSystemStatus_35e6f25e-5078-4df9-a8ff-0a9baf5da69a)
[Homebridge] [12/16/2019, 20:03:36][SmartThings]ALERT: Total Initialization Time: (4 seconds)
[Homebridge] [12/16/2019, 20:03:36][SmartThings]NOTICE: Unknown Capabilities: ["Three Axis"]
[Homebridge] [12/16/2019, 20:03:36][SmartThings]INFO: SmartThings DeviceCache Size: (2)
[Homebridge] [12/16/2019, 20:03:36][SmartThings]INFO: WebServer Initiated...
[Homebridge] [12/16/2019, 20:03:36][SmartThings]INFO: Sending StartDirect Request to SmartThings | SendToLocalHub: (false)
[Homebridge] [12/16/2019, 20:03:36][SmartThings]INFO: Direct Connect Active | Listening at 10.0.0.30:8000
[Homebridge] [12/16/2019, 20:03:37][SmartThings]ERROR: sendStartDirect Error:  404 - {"error":true,"type":"SmartAppException","message":"Not Found"}
Unable to determine plugin type for "homebridge-smartthings-v2"

**Comment by tonesto7** [comment]
I donated and downloaded an image for hoobs.  I will try to get it installed and see what hoobs is doing differently

**Comment by bloody193** [comment]
> I donated and downloaded an image for hoobs. I will try to get it installed and see what hoobs is doing differently

Oh Wow that's above and Beyond the call of duty but Thank You. Im new to all this and learning as I go. I had  it working perfectly on hoobs 2.0 and the previous version homebridge-smartthings by you.  Thanks to yourself and this wonderful community.

**Comment by bloody193** [comment]
> I donated and downloaded an image for hoobs. I will try to get it installed and see what hoobs is doing differently
This can be found on the hoobs github located below. Hope that helps. 
https://github.com/hoobs-org/HOOBS/wiki/3.8-Configuration
Plugins

Each plugin you install will show in the config. We seperate each plugin into it's own section. This helps with keeping everything straight.

Plugins can contain a configuration schema. This is what we use to make the fields. If your favorite plugin doesn't have a configuration schema, add an issue on their GitHub repository and direct them to this document.
https://github.com/hoobs-org/HOOBS/wiki/6.4-Developing-Plugins

**Comment by tonesto7** [comment]
I'm not sure what to do with this issue.  Since the Hoobs interface was based on the config-ui-x plugin it supports the config.schema.json file which is included in the project.  For some reason, it doesn't want to show the config for this plugin.  Maybe you can open up an issue on Hoobs?

**Comment by tonesto7** [comment]
@bloody193 

> [Homebridge] [12/16/2019, 20:03:37][SmartThings]ERROR: sendStartDirect Error: 404 - {"error":true,"type":"SmartAppException","message":"Not Found"}
Unable to determine plugin type for "homebridge-smartthings-v2"

Not sure why this didn't stick out to me before but this is a problem.  It doesn't see or can't reach the smartapp endpoint.

Maybe the config is invalid or something but I should be a simple copy and paste from the smartapp info.

**Comment by bloody193** [comment]
> FYI. I use hoobs and when I installed STHBv2 it placed a few lines as a placeholder for the platform in the config automatically. Although to see it you have to go into the whole config file in advanced as compared to just seeing the applicable code which is a new function in hoobs 3, vs 2. Then I just copied and paste the code from the smartapp into the config.
> […](#)

Thanks , mind sharing a example of the config you have for version 2.

**Comment by tonesto7** [comment]
Mine is basically just like this:
https://github.com/tonesto7/homebridge-smartthings-v2#configjson-settings-example

There is something definitely wrong with the new config section in Hoobs v3.x

**Comment by mkellsy** [comment]
HOOBS was not loading this plugin because of an issue in our code. Fixed in 3.1.11.

The configuration issue is because there is a missing object in the schema. I corrected this in Pull Request #30

**Comment by tonesto7** [comment]
@mkellsy  I just released v2.1.  I think it's ready to begin certification

**Comment by mkellsy** [comment]
Awesome. I will start the process.
