### ISSUE TITLE
Smartthings device command not recognized in HB [question]

### ISSUE THREAD

**Issue by hurdleguy** [tonesto7/homebridge-smartthings-v2#18]
Hello, 

Recently updated to V2 of the ST homebridge via the community installer and updated the JSON to reflect the new plugin. Home app recognizes all my devices in my smartthings app but when trying to send a signal to turn on/off lights, it just hangs. Looking at log files, it seems that there is no "value" to the signal from ST to HB. Can someone point me to the right direction of how to fix it? 

When changing to not send send as local commands, the command works, but it takes a very noticeable delay before the command goes through which at that point, is quick to close the home app and open ST app to turn on/off lights

Image of issue log with local commands on: https://imgur.com/a/mZFSCdY

**Comment by tonesto7** [comment]
I don't see anything wrong with that command.  The value nothing means the device doesn't have a value passed with the command name.

As far as the commands being slow I'm pretty sure ST was having issues with device control right around the time you were testing this.

**Comment by hurdleguy** [comment]
As of today, using ST app has nearly instant feedback when pressing a tile. 

when using the ST-v2 plugin and setting the option of sending commands locally, my commands from the home app would never get through and it would hang indefinitely whereas turning the option to send commands locally off, then it would work, just frustratingly slow. 

Am I doing something wrong?

This is running on a pi3b+ on HOOBS platform if that matters at all.

**Comment by charis0728** [comment]
I have a similar problem.
A command from Homebridge works well but a command from ST doesn't work.
To test this problem, I made a virtual switch on ST and I checked that it is shown on Apple Home app.
When I turned on and off the switch in Homekit, the switch in ST turned on and off also.
But I tried to turn on and off the Homekit switch, the ST switch didn't work.
Is this a normal situation? Can you please check this problem?

**Comment by tonesto7** [comment]
Should be resolved in the new v2.1.0 I just pushed out.
