### ISSUE TITLE
3-speed fan device type (BUG) 

### ISSUE THREAD

**Issue by swamplynx** [tonesto7/homebridge-smartthings-v2#21]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The SmartApp and Device Handler are using the latest code available.
-  [X] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 44
-  SmartApp Version: Latest
-  Device Handler Version: Latest
-  Homebridge Version: Latest

## Expected Behavior
**Tell us what you think should be happening**

I tested the new 3-speed fan device type available in the SmartApp with a Jasco 3-speed fan controller using the default local execution DTH (Dimmer). When using the Fan device type the device shows in HomeKit as a 0-100% variable speed fan (expected). When using the 3-speed fan device type it just shows up as a dimmer light. I have no idea of HomeKit has a specific device type for 3-speed fans, but guessing the intention is that it does not show up as a dimmer light.

**Comment by tonesto7** [comment]
@swamplynx  So you selected the fan in the smartapp under the 3-speed Input?

Unfortunately, The home app doesn't support the speeds in the UI. 
I created the inputs in the app to help set the increment values of the slider in the home app, but it doesn't seem to work like the characteristics describes.
