### ISSUE TITLE
Filtering out Button capability from a device does not remove the extra button from Home app 

### ISSUE THREAD

**Issue by cnnn** [tonesto7/homebridge-smartthings-v2#22]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The SmartApp and Device Handler are using the latest code available.
-  [x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 4
-  Mobile App Version(Not required):
-  SmartApp Version: 2.0.3
-  Device Handler Version: 2.0.10
-  Homebridge Version: 0.4.50
-  NodeJS Version: 8.11.1

## Expected Behavior
After removing Button capability from a device, the button is should disappear from Home app.

## Current Behavior
After removing Button capability from a device, the button is still showing up in Home app.

## Steps to Reproduce (for bugs)
1. Add a device with both Switch and Button capabilities to SmartThings
2. In the smart app, add the device to HomeKit as Switch (without removing the Button capability)
3. Once Home app shows a switch and a button for the device, go back to smart app and remove the Switch capability

## Context
My GE/Jasco in-wall switch has both Switch and Button capabilities thanks to the DH of "nuttytree : GE/Jasco Z-Wave Plus Dimmer Switch" so I can configure double press behavior. However both v1 and v2 of the plugin renders the switch only as Button in HomeKit, even though I define the type as Switch or Light in the smart app. The solution is to remove the Button capability with the filtering. While doing this after the device already shows up as both Button and Switch, I discovered this issue. I am able to workaround it by unchecking the device as Switch then adding it back. 

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
This is one of the items that will be addressed in v2.1.x.  It's currently in testing phases right now I expect to roll it out hopefully before the new year.

**Comment by tonesto7** [comment]
Should be resolved in the new v2.1.0 I just pushed out.
