### ISSUE TITLE
Will this work without a hub?

### ISSUE THREAD

**Issue by paqpaqpaq** [tonesto7/homebridge-smartthings-v2#25]
Will this plugin function without a hub?
I have some robot vacuum cleaners I would like to add, however via Smartthings IDE, I see no option to enter your repo. Is this because I do not have a smartthings hub? (My device are present in the IDE though)

**Comment by tonesto7** [comment]
While a hub is not required I don’t think you can create a SmartThings location in the IDE without one.

**Comment by paqpaqpaq** [comment]
> While a hub is not required I don’t think you can create a SmartThings location in the IDE without one.

I actually do have locations in my IDE.
Also my devices have a device network ID, with execution location 'cloud'

**Comment by paqpaqpaq** [comment]
@tonesto7 
I installed your repo and plugin in the app. (1 vacuum cleaner as other device / switch)
2 homekit buttons pop up. 1 'security' (home) and 1 switch (the vacuum)
The switch shows battery is almost empty. The switch does function, however nothing happens

> [2020-1-8 11:32:50][SmartThings-v2]NOTICE: Sending Device Command: on | Value: Nothing | DeviceID: (C0972764-2564-0000-0000-000000000000) | SendToLocalHub: (false)

I point out that I can see all settings and status of the vacuum in the smartthings classic app, however I can't operate from there either. It works just fine from the smartthings app though.

debug:
> [2020-1-8 11:38:47][SmartThings-v2]GOOD: [CHARACTERISTIC (function () {
>   Characteristic.call(this, 'On', '00000025-0000-1000-8000-0026BB765291');
>   this.setProps({
>     format: Characteristic.Formats.BOOL,
>     perms: [Characteristic.Perms.READ, Characteristic.Perms.WRITE, Characteristic.Perms.NOTIFY]
>   });
>   this.value = this.getDefaultValue();
> }) GET] switch (willem II) | LastUpdate: (Wed Jan 08 2020 11:38:33 GMT+0100 (CET)) | Value: (false)
> [2020-1-8 11:38:47][SmartThings-v2]GOOD: [CHARACTERISTIC (function () {
>   Characteristic.call(this, 'On', '00000025-0000-1000-8000-0026BB765291');
>   this.setProps({
>     format: Characteristic.Formats.BOOL,
>     perms: [Characteristic.Perms.READ, Characteristic.Perms.WRITE, Characteristic.Perms.NOTIFY]
>   });
>   this.value = this.getDefaultValue();
> }) GET] switch (willem II) | LastUpdate: (Wed Jan 08 2020 11:38:33 GMT+0100 (CET)) | Value: (false)
> [2020-1-8 11:38:47][SmartThings-v2]GOOD: [CHARACTERISTIC (function () {
>   Characteristic.call(this, 'Status Low Battery', '00000079-0000-1000-8000-0026BB765291');
>   this.setProps({
>     format: Characteristic.Formats.UINT8,
>     maxValue: 1,
>     minValue: 0,
>     validValues: [0,1],
>     perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
>   });
>   this.value = this.getDefaultValue();
> }) GET] battery (willem II) | LastUpdate: (Wed Jan 08 2020 11:38:33 GMT+0100 (CET)) | Value: (1)
> [2020-1-8 11:38:47][SmartThings-v2]GOOD: [CHARACTERISTIC (function () {
>   Characteristic.call(this, 'Status Low Battery', '00000079-0000-1000-8000-0026BB765291');
>   this.setProps({
>     format: Characteristic.Formats.UINT8,
>     maxValue: 1,
>     minValue: 0,
>     validValues: [0,1],
>     perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
>   });
>   this.value = this.getDefaultValue();
> }) GET] battery (willem II) | LastUpdate: (Wed Jan 08 2020 11:38:33 GMT+0100 (CET)) | Value: (1)


`[2020-1-8 11:53:05][SmartThings-v2]NOTICE: Unknown Capabilities: ["Ocf","Execute","Remote Control Status","Robot Cleaner Cleaning Mode","Robot Cleaner Movement","Robot Cleaner Turbo Mode","custom.robotCleanerSmartTurboMode","custom.robotCleanerSoundSet","custom.robotCleanerSmartControl","custom.robotCleanerRepeatCleanOption","custom.robotCleanerBatteryFullStatus","custom.robotCleanerRepeatCleanSupport","custom.robotCleanerSuctionType","custom.robotCleanerHistorySupport","custom.robotCleanerEnergyMonitorSupport","custom.robotCleanerReserveCleanType","custom.robotCleanerHrmSupport","custom.robotCleanerBehavior","custom.error","custom.disabledCapabilities","custom.dthVersion"]`
