### ISSUE TITLE
(BUG) Security Alarm Displaying when No Such Device Exists

### ISSUE THREAD

**Issue by apabari** [tonesto7/homebridge-smartthings-v2#26]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The SmartApp and Device Handler are using the latest code available.
-  [ ] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 4
-  Mobile App Version(Not required):
-  SmartApp Version: 2.0.4
-  Device Handler Version: unsure
-  Homebridge Version:  0.4.50
-  NodeJS Version: 10.15.2

## Expected Behavior
Apple Home should display two Z-Wave Switches and one Water Sensor

## Current Behavior
**What happens instead of the expected behavior?**
Apple Home displays two Z-Wave Switches, one Water Sensor, AND a Security Alarm

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**
Trying to enable Apple Homekit to control the Z-Wave Devices that are currently controlled by my Samsung Smartthings Hub

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
@apabari There is a toggle in the SmartApp that enables SHM (Smart Home Monitor) control for SmartThings.  Disable it and the security device will disappear.
