### ISSUE TITLE
(BUG)  Button accessory does not function correctly

### ISSUE THREAD

**Issue by cladmonitor** [tonesto7/homebridge-smartthings-v2#27]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The SmartApp and Device Handler are using the latest code available.
-  [ x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: All
-  Mobile App Version(Not required): 
-  SmartApp Version: 2.0.3
-  Device Handler Version: Not using any DH
-  Homebridge Version:  0.4.50
-  NodeJS Version:  9.8.0

## Expected Behavior
1. Pressing button should get passed to Homekit as a Button Press in correct order

## Current Behavior
1. Single press does get logged in console but Homekit does not receive this action. A double press works as intended, if after a double press you do a single press it works properly only once. 

## Steps to Reproduce (for bugs)
No code or other relevant details other than this started after I migrated to v2

## Context
Button presses are useless atm.

---
PLease ask for anything specific to this since console outputs look normal I don't know what specifically needs to be logged for support.

**Comment by tonesto7** [comment]
@cladmonitor i will investigate and get a fix out

**Comment by tonesto7** [comment]
@cladmonitor So i'm embarassed to say that I haven't really tested the buttons but can confirm they are completely broken.  
I don't know how they ever worked.   I'm working on rebuilding the button logic right now.   Either way my fixes will be pushed out in the v2.1 release that should be ready right after the new year.

**Comment by cladmonitor** [comment]
@tonesto7 I’m glad I’m not crazy but they did work with the old v1 stuff, can’t recall how old it was but was a feature I used everyday (single double and long press) regardless I’m really impressed you jumped on it so quickly! Thank you for the support!

**Comment by tonesto7** [comment]
@cladmonitor Can you explain to me how you are using these buttons under Homekit?

I didn't convert the previous button logic so i'm not familiar with how it's expected to work.
To me it doesn't seem to function like a button in the Home app.  It also me to define actions for each button event type (pressed, held, double tap), but it's never designed to send a command back to ST as if the button was pressed.

I've been thinking about allowing users to create virtual buttons that can be used to trigger automations under homekit, but not have them tied to anything under smartthings.

**Comment by tonesto7** [comment]
Should be resolved in the new v2.1.0 I just pushed out.
