### ISSUE TITLE
[Feature Request] Motion Sensors/Smoke Detectors not showing under SmartThings options

### ISSUE THREAD

**Issue by Casuallynoted** [tonesto7/homebridge-smartthings-v2#3]
**Is your feature request related to a problem? Please describe.**
I’m looking to use this plugin together with:

https://github.com/csdozier/device-concord4

This Smartapp, which creates four object types for a security system-

An alarm system (appears to be shown in HomeKit despite not being selected)
Contact sensors (showing up in the sensors menu on the Smartapp and appears in HomeKit)
Motion sensors (shows up in SmartThings as a thing, but not under any menu in the Smartapp and not in HomeKit)
Smoke detectors (same as the motion sensors)

**Describe the solution you'd like**
I’m hoping to find a way to access and use those other two device types in HomeKit for automations, etc.

**Describe alternatives you've considered**
At the moment I’m not entirely sure if there are any alternatives for Concord4 systems that might work better (or at all) with HomeKit, but I’m actively searching.

**Comment by tonesto7** [comment]
This plugin is not done yet.  It’s a complete rewrite of the original.
