### ISSUE TITLE
[Feature Request] Add Support for Power Strip Characteristic

### ISSUE THREAD

**Issue by roberkane212** [tonesto7/homebridge-smartthings-v2#32]
is there anyway we can get the power strip feature in HomeKit for power strips that work with SmartThings?

**Comment by tonesto7** [comment]
@roberkane212 Do you have an examples where it's being used?
I'm not familiar with any HomeKit characteristics specific to power strips.

**Comment by roberkane212** [comment]
![62683B20-087C-483C-BAD7-FA5FB61B653A](https://user-images.githubusercontent.com/44589993/71549371-4b134080-298a-11ea-92de-686606cceb45.png)

**Comment by roberkane212** [comment]
![AB2040BC-4B93-4D84-B847-0E4001D9AD20](https://user-images.githubusercontent.com/44589993/71549435-34211e00-298b-11ea-9641-560ca0fe237f.jpeg)

**Comment by tonesto7** [comment]
That's pretty cool...  I bet its a custom characteristic that they used.  I will see what i can find.

**Comment by roberkane212** [comment]
Yes it came with iOS 13, thanks for looking into it

**Comment by tonesto7** [comment]
@roberkane212 What type of devices are these? I'm trying to find the characteristics that are used and not finding much.

**Comment by tonesto7** [comment]
Nvm... I see it plain as day in the screen shot

**Comment by roberkane212** [comment]
@tonesto7 lol ok great, I’d really like to see this. Also have you got any word on the new update? I’ve downgraded to v2.0.10 so all my stuff can work again

**Comment by tonesto7** [comment]
> lol ok great, I’d really like to see this.

I would like to see the powerstrips as well, but so far all my searches have turned up empty.

> Also have you got any word on the new update? I’ve downgraded to v2.0.10 so all my stuff can work again

I have the next update ready and I have 144 other accessories along with 5 buttons added and it's working flawlessly.  
I am waiting till I get home from work to try with the new SmartThings button I ordered before ruling this a success.
I also took the time to fix about a dozen other bugs with this new version outside of the buttons too.

One thing I discovered is that sometimes you need to open the home app once after restarting the plugin for the button automation events to work (don't know why)

**Comment by tonesto7** [comment]
@roberkane212  Can you send me a screenshot of the strips button control page?

**Comment by roberkane212** [comment]
![4A749560-26DC-4BE6-8F62-97B76EF0FB33](https://user-images.githubusercontent.com/44589993/72575027-1dd6f580-3899-11ea-9c79-4463a34c4c6f.jpeg)
@tonesto7

**Comment by roberkane212** [comment]
@tonesto7 sorry I took so long and hope this is what you were asking for

**Comment by roberkane212** [comment]
@tonesto7 Since you have experience with ST community, do you know how I can report an issue with an accessory? My plugs come up as switches in ST app. So I’m sure if I add them to the plugin they will do the same

**Comment by tonesto7** [comment]
@roberkane212 Thanks that was what I was looking for.
I should be able to emulate this (minus the powerstrip icon.
I'll add it to the board of features for the next release.

**Comment by roberkane212** [comment]
@tonesto7 awesome you’re the best!!!

**Comment by roberkane212** [comment]
@tonesto7 im using the TPLink hs 300 power strip. Hoping it will be able to work!!!

**Comment by roberkane212** [comment]
@tonesto7 is this now workable in the new update?

**Comment by roberkane212** [comment]
Just trying to figure out if it was so I can figure out if mine is working. Currently it is not

**Comment by tonesto7** [comment]
I haven't even started on it. I wanted to get v2.2 out.
Implementing in the plugin will be rather simple, it's defining them as power strips in the smartapp that will be tricky because all of the plugs show up as individual devices up in ST.

The more I think of this, what real benefit will adding these to a single accessory provide?

**Comment by roberkane212** [comment]
@tonesto7 well if it’s becoming a bother or is taking too much effort my all means abandon the project. I much rather you put your efforts in the plugin as a whole. Just thought I was a nice idea to be able control all plugs in one place without having to go into accessories to get to them if they are on tile. However like I said if it’s gonna take too much time or no one else is really interested close it

**Comment by tonesto7** [comment]
I wasn’t saying it wasn’t worth it just trying to gauge the benefit.  I will tinker with the app tonight

**Comment by roberkane212** [comment]
@tonesto7 ok thanks, however like I said if it becomes too much trouble don’t worry about it. I appreciate all your work and quick responses

**Comment by roberkane212** [comment]
Thanks for the try @tonesto7
