### ISSUE TITLE
Homebridge plugin delays receiving/processing some events from SmartThings

### ISSUE THREAD

**Issue by devarshi** [tonesto7/homebridge-smartthings-v2#33]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The SmartApp and Device Handler are using the latest code available.
-  [ x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 43
-  Mobile App Version(Not required): 
-  SmartApp Version: 2.0.4
-  Device Handler Version: 
-  Homebridge Version: 0.4.50, Homebridge plugin version: 2.0.10
-  NodeJS Version:10.15.2

## Expected Behavior
**Tell us what you think should be happening**
Events (sensor state, lock/unlock, etc.) should propagate from SmartThings to Homebridge nearly instantaneously. 

## Current Behavior
**What happens instead of the expected behavior?**
Some events propagate right away, others experience a 8-30 second delay. 
ps. This issue did not exist with the homebridge-smartthings v1 smartapp & plugins.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Configure multiple sensors. at least one contact sensor and a motion sensor. 
2. Trigger the sensor(s)
3. Notice that HomeKit alerts / state updates for the contact sensor are delayed.
4.

TBH, unsure if others are experiencing this issue, but I can easily reproduce it. 

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

Homekit alerts are delayed, as are automations in Homekit that rely on these events. This also degrades the UX b/c actions (like locking a door) take longer to reflect on the Home app UI (which, for instance, gets stuck on "Locking..." for that time). 

---
Please include a copy of any relevant log output to assist in tracking down the bug

### Motion events propagating instantaneously

SmartThings log: 
`xxxxxxxxx-333f-4112-9303-3d9001a1718c  2:26:05 PM: debug Sending DEVICE Event (Office | MOTION: active) to Homebridge at (10.0.1.x:8000)`

Homebridge log:
`[12/28/2019, 2:26:05 PM] [INFO]: [Device Change Event]: (Office) [MOTION] is active`

### Door lock / unlock event takes 10+ seconds to propagate. Have also seen this delay with contact sensors. 

SmartThings log: 
`xxxxxxxxx-333f-4112-9303-3d9001a1718c  2:36:13 PM: debug Sending DEVICE Event (Garage door lock | LOCK: locked) to Homebridge at (10.0.1.x:8000)`

Homebridge log (notice the 16 second delay):
`[12/28/2019, 2:36:29 PM] [INFO]: [Device Change Event]: (Garage door lock) [LOCK] is locked`

**Comment by devarshi** [comment]
Update: I added some more logging. Looks like there's a delay in the plugin receiving the event update webhook. Unsure if this is a hub issue or somewhere else.

SmartApp -- 
`xxxxxxxxx-333f-4112-9303-3d9001a1718c  4:11:12 PM: debug Sending DEVICE Event (Garage door lock | LOCKSTATUS: Battery 73%) to Homebridge at (10.0.1.x:8000)`
`xxxxxxxxx-333f-4112-9303-3d9001a1718c  4:11:12 PM: debug Sending DEVICE Event (Garage door lock | LOCK: unlocked) to Homebridge at (10.0.1.x:8000)`

Homekit plugin -- 

`Dec 28 16:11:12 homebridge[23885]: [12/28/2019, 4:11:12 PM][SmartThings-v2]DEBUG: webApp.post update request:  lockStatus d862f408-8a0e-44be-a956-88fc2969866e`
`Dec 28 16:11:12 homebridge[23885]: [12/28/2019, 4:11:12 PM][SmartThings-v2]DEBUG: Processing Device Attribute Update:  lockStatus d862f408-8a0e-44be-a956-88fc2969866e`

`Dec 28 16:11:20 homebridge[23885]: [12/28/2019, 4:11:20 PM][SmartThings-v2]DEBUG: webApp.post update request:  lock d862f408-8a0e-44be-a956-88fc2969866e`
`Dec 28 16:11:20 homebridge[23885]: [12/28/2019, 4:11:20 PM][SmartThings-v2]DEBUG: Processing Device Attribute Update:  lock d862f408-8a0e-44be-a956-88fc2969866e`
`Dec 28 16:11:20 homebridge[23885]: [12/28/2019, 4:11:20 PM][SmartThings-v2]DEBUG: Finished device attrib update:  lock d862f408-8a0e-44be-a956-88fc2969866e`
`Dec 28 16:11:20 homebridge[23885]: [12/28/2019, 4:11:20 PM][SmartThings-v2]INFO: [Device Change Event]: (Garage door lock) [LOCK] is unlocked`

**Comment by devarshi** [comment]
So, on further investigation, may be this is happening because of leaving a promise unresolved? The `LOCKSTATUS` characteristic doesn't exist in HomeKit, which triggers this condition below -

https://github.com/tonesto7/homebridge-smartthings-v2/blob/6aa2e2088eec73872bb212b0b0293fd205cff075/src/ST_Accessories.js#L294

I played around with resolving the promise in this scenario, and that seems to fix the delay issue. But I'm not very familiar with promises, so just consider this a helpful exploration :).

**Comment by tonesto7** [comment]
@devarshi Thanks a lot for looking into it.  I will see what I can find now that you pointed me in a specific direction.

**Comment by tonesto7** [comment]
I've applied your findings to the code under my dev branch and it seems to be running better

**Comment by tonesto7** [comment]
Should be resolved in the new v2.1.0 I just pushed out.
