### ISSUE TITLE
Question: Does this allow anything supported by the SmartThings hub to be seen on HomeKit

### ISSUE THREAD

**Issue by scoobaspeaz** [tonesto7/homebridge-smartthings-v2#35]
This is probably a really dumb question but I notice the list of devices that the SmartThings hub connects to is long. Does this allow any device supported by SmartThings hub to also be supported in HomeKit via this Homebridge plugin?

**Comment by tonesto7** [comment]
For the most part yes... There are certain attributes under ST that don't have a matching characteristic in HomeKit.  
I don't have a list but you can easily experiment
