### ISSUE TITLE
(BUG) Plug In Sends Events Locally Even When Switched Off

### ISSUE THREAD

**Issue by hlipnick** [tonesto7/homebridge-smartthings-v2#36]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The SmartApp and Device Handler are using the latest code available.
-  [x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 3
-  Mobile App Version(Not required):
-  SmartApp Version: 2.0.4
-  Device Handler Version: ?
-  Homebridge Version: HOOBS 3.1.15
-  NodeJS Version:  v12.13.1

## Expected Behavior
The smart app does not seem to retain settings.  When I go through and add a device, it is added to homebridge, but if I come back to the SmartApp in SmartThings (Classic), the SmartApp interface appears like new.  This is causing the "Send Local Commands" toggle switch to persist to the on state, and the plug in is sending local commands to the hub: "| SendToLocalHub: (true)", even though the JSON config has both "local_commands": false & "direct": false.

This is causing switches to hang in the Home app after one activation, and seemingly shutting things down on the homebridge side:

From the terminal output, even when set for local_commands false
"[Homebridge] [1/1/2020, 23:26:43][SmartThings-v2]NOTICE: Updating Global Values | HubIP: 192.168.1.133 | UseLocal: true"

Eventually I get this:
[Homebridge] [1/2/2020, 08:30:35] Unhandled Rejection "RequestError: Error: connect ETIMEDOUT 192.168.1.133:39500".
[Homebridge] [1/2/2020, 08:30:35] Unhandled Rejection "TypeError: callback is not a function".
[Homebridge] [1/2/2020, 08:30:35] RequestError: Error: connect ETIMEDOUT 192.168.1.133:39500
[Homebridge] at new RequestError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:14:15)
[Homebridge] at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:87:29)
[Homebridge] at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
[Homebridge] at self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
[Homebridge] at Request.emit (events.js:210:5)
[Homebridge] at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request/request.js:881:8)
[Homebridge] at ClientRequest.emit (events.js:210:5)
[Homebridge] at Socket.socketErrorListener (_http_client.js:406:9)
[Homebridge] at Socket.emit (events.js:210:5)
[Homebridge] at emitErrorNT (internal/streams/destroy.js:92:8)
[Homebridge] at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
[Homebridge] at processTicksAndRejections (internal/process/task_queues.js:80:21)
[Homebridge] [1/2/2020, 08:30:35] TypeError: callback is not a function
[Homebridge] at /home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/ST_Client.js:112:21
[Homebridge] at processTicksAndRejections (internal/process/task_queues.js:93:5)
[Homebridge] (node:7884) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[Homebridge] (node:7884) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)

## Current Behavior
**What happens instead of the expected behavior?**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
Should be resolved in the new v2.1.0 I just pushed out.
