### ISSUE TITLE
(BUG) Samsung Smartthings Motion Sensor and Multipurpose Sensor - no status update

### ISSUE THREAD

**Issue by Damianeq90** [tonesto7/homebridge-smartthings-v2#37]
## Check the following before opening the problem

** Go through all the points below and put "x" in all the appropriate fields.
If you're unsure about any of them, don't hesitate to ask. We are here to help! **

- [x] That _OAuth_ is enabled for SmartApp in the IDE.
- [x] SmartApp and Device Handler use the latest available code.
- [x] That both SmartApps and device support modules have been _published for you_ in the IDE.

---
## Configuration information
- How many devices are detected?: All (14)
- Mobile application version (not required):
- SmartApp version: 2.0.4
- Device support module version:
- Homebridge version: QNAP Homebridge - homebridge-config-ui-x v4.6.7 - node.js v12.14.0 - © 2019 oznu
- NodeJS version:

## Expected behavior
Hombridge does not refresh the status of motion sensor devices and Multipurpose Sensor data is downloaded only once when you reset your homebridge. No update of the motion detection status. no update of door opening or closing, no temperature update from the device

## Current behavior
The SmartThings application receives data correctly, but you cannot see it in the homebridge.

## Steps to Reproduce (in case of errors)
** Provide a link to a live example or unique set of steps to reproduce this error. If necessary, attach a code to play **

1.
2)
3)
4

## Context
** How did this problem affect you? What are you trying to achieve
The ability to automate from Apple Home
** Providing context helps us find the solution that is most useful in the real world **

---
Include a copy of the appropriate log output to help track the error

**Comment by tonesto7** [comment]
There a new release v2.1 release coming in the next few days that will hopefully resolve this issue,

**Comment by tonesto7** [comment]
Should be resolved in the new v2.1.0 I just pushed out.

**Comment by Damianeq90** [comment]
Despite the update, motion sensors do not update their status.

**Comment by Damianeq90** [comment]
Sorry, it works, I did it: 1 npm update -g
2 npm cache clean -f
3 sudo n stable
4 npm install -g -unsafe-perm homebridge @ latest -g and detectors have started updating status

**Comment by domoarigato56** [comment]
Attempting the fix from Damianeq90, 
Step 3 `sudo n stable` returns the following error:

curl: (60) SSL certificate problem: unable to get local issuer certificate

Is there a command I can copy/paste to bypass the SSL certificate issue? I am very new to all of this.
