### ISSUE TITLE
SmartThings v2 with google nest login

### ISSUE THREAD

**Issue by sjmarkham** [tonesto7/homebridge-smartthings-v2#39]
I upgraded to v2 and everything was working fine but nest stopped working with my username password.  I switched to a google account and then followed all the steps to get auth codes from google.  I updated my config.json with all the new info but when homebridge reboots all my SmartThings devices show as failed to update.  I take the google auth out for homebridge-nest reboot and everything works as before.  So need some advice as where to look to get both SmartThings and nest to work under homebridge.

**Comment by tonesto7** [comment]
How many devices are you bringing in from SmartThings into HomeKit?

Each HomeKit bridge is allowed 149 accessories.  So if the number of devices combined for ST and Nest are > than 149 the plugin will fail to start

**Comment by sjmarkham** [comment]
31 I believe and nest worked fine with SmartThings until I had to switch to the google authentication.

**Comment by tonesto7** [comment]
You really should look at the logs for homebridge after restarting the bridge
