### ISSUE TITLE
Cannot see my devices in homekit

### ISSUE THREAD

**Issue by tylorgoodine99** [tonesto7/homebridge-smartthings-v2#41]
I've followed all of the instructions and when I set it all up in the smartthings app it said that I dont have to do anything else accept type in these numbers...

So I need help!

**Comment by scoobaspeaz** [comment]
did you use the SmartThings app or the Homebridge v2 app within the SmartApp section of the SmartThings app?  You have to configure the devices in the Homebridge v2 app before Homebridge will see it and then it will show up in HomeKit.

**Comment by tonesto7** [comment]
@tylorgoodine99  Definitely going to need more details
