### ISSUE TITLE
How do you update the SmartApp?

### ISSUE THREAD

**Issue by scoobaspeaz** [tonesto7/homebridge-smartthings-v2#42]
How do you update the SmartApp from one version to another without just removing it first?

**Comment by tonesto7** [comment]
Just overwrite the code

**Comment by scoobaspeaz** [comment]
On my phone it still shows the old version. I updated from the repo on my SmartThings IDE. 
![6CE1E140-314E-4BA1-B95B-F775D8DBA2B2](https://user-images.githubusercontent.com/5273311/71940118-2fc2e500-3183-11ea-9307-b9e893a6998e.png)

**Comment by scoobaspeaz** [comment]
Figured it out. After I updated from the repo I didn't know I also had to click on the app from the smart apps section of the IDE and then click publish (for me). After I did that step I was able to see the new version in my SmartThings app and the app changed from edited to published on the IDE.
