### ISSUE TITLE
(BUG) Issue after 2.1.0 update

### ISSUE THREAD

**Issue by flynhawaiian** [tonesto7/homebridge-smartthings-v2#43]
[Homebridge] [1/7/2020, 5:16:42 PM] TypeError: transport is not a constructor
    at exports.Logger.Logger.add (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/node_modules/winston/lib/winston/logger.js:481:41)
    at Logging.getLogger (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/libs/Logger.js:58:20)
    at new ST_Platform (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/ST_Platform.js:32:33)
    at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:293:34)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[Homebridge] [1/7/2020, 5:16:42 PM][SmartThings-v2]ERROR: uncaughtException: transport is not a constructor
[Homebridge] [1/7/2020, 5:16:42 PM] Got SIGTERM, shutting down service...

**Comment by flynhawaiian** [comment]
Using HOOBS v3 newest version if that helps

**Comment by rahoolio** [comment]
I'm not sure if its the exact same issue, but I'm not able to start the service after the update. Are you experiencing this as well?

**Comment by flynhawaiian** [comment]
yes.

**Comment by tonesto7** [comment]
@rahoolio Are you running under Hoobs as well?

**Comment by rahoolio** [comment]
Yes sir. I had to restore from a backup.

**Comment by flynhawaiian** [comment]
I'm running both the new app and the new update of stv2

**Comment by flynhawaiian** [comment]
winston logger update needed or node.js update needed?

**Comment by flynhawaiian** [comment]
hoobs@hoobs:~/.hoobs/etc $ node -v
v10.16.3

**Comment by rahoolio** [comment]
Same. Newest on the app(2.1.0), as well as Hoobs (Version 3.1.19), node -v v12.13.1, npm -v 6.13.4

**Comment by flynhawaiian** [comment]
hoobs@hoobs:~/.hoobs/etc $ npm -v
6.13.4

**Comment by rahoolio** [comment]
Oh, I'll try again, but when I went to uninstall the plugin to try to reinstall it, it would not uninstall which is what led to the restore

**Comment by lawrencyous** [comment]
well, i have the same issue! also, everythings new!..

**Comment by rahoolio** [comment]
Here is what I get when I try to uninstall the newest version.
> [Homebridge] [1/7/2020, 20:55:57][SmartThings-v2]ERROR: uncaughtException: transport is not a constructor
> [Homebridge] [1/7/2020, 20:55:57] Got SIGTERM, shutting down service...
> npm
> ERR! code EEXIST
> npm ERR! path /home/hoobs/.hoobs/node_modules/.bin/logrotate-stream
> npm
>  ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/.bin/logrotate-stream: is outside /home/hoobs/.hoobs/node_modules/logrotate-stream and not a link
> npm ERR! File exists: /home/hoobs/.hoobs/node_modules/.bin/logrotate-stream
> npm
> ERR! Remove the existing file and try again, or run npm
> npm ERR! with --force to overwrite files recklessly.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/hoobs/.npm/_logs/2020-01-08T01_56_38_061Z-debug.log

I'm considering now that this may be a separate issue so I can move it if need be

**Comment by flynhawaiian** [comment]
I'm doing a fresh hoobs install right now.

**Comment by flynhawaiian** [comment]
Didn't help

**Comment by rahoolio** [comment]
> Didn't help

Appreciate you sacrificing the time to try

**Comment by lawrencyous** [comment]
> Didn't help



> > Didn't help
> 
> Appreciate you sacrificing the time to try

me too, i was right about to reeinstall everything..

**Comment by flynhawaiian** [comment]
No problem.  Figured it would cure the issue :(

**Comment by tonesto7** [comment]
I’m going to need to spin up my Hoobs instance and test it

**Comment by rahoolio** [comment]
We appreciate you

**Comment by flynhawaiian** [comment]
> I’m going to need to spin up my Hoobs instance and test it

Thanks

**Comment by flynhawaiian** [comment]
More reported issues on the Hoobs Facebook page.

**Comment by tonesto7** [comment]
I'm trying to work through HOOBs right now and see if I can duplicate the error

**Comment by flynhawaiian** [comment]
I did a fresh install with my RPi3b+ using the 3.1.19 then installed the homebridge-smartthings-v2 app using the plugin installer on the hoobs.local page.  Installed; then pulled the configuration file from the app.

**Comment by tonesto7** [comment]
So I am able to duplicate this... I'm just not sure why it's throwing the error only on Hoobs.  It works fine on all other platforms.

**Comment by flynhawaiian** [comment]
My guess is it has to do with a node js mismatch?  What node js are you using on your other platform?

**Comment by tonesto7** [comment]
I think Hoobs uses a new version of the Winston package globally.  I'm working on targetting the version defined in the code... Standby

**Comment by flynhawaiian** [comment]
Found it: winston@2.1.1

**Comment by tonesto7** [comment]
where did you find that?

**Comment by flynhawaiian** [comment]
npm list -g

**Comment by tonesto7** [comment]
The weird part is that i'm targetting winston@2.4.4 and based on that error we are seeing that it's getting a winston@3.0.0+

**Comment by flynhawaiian** [comment]
I can try to update to 2.4.4 and see if that fixes it?

**Comment by flynhawaiian** [comment]
Nope didn't seem to do the trick

**Comment by tonesto7** [comment]
If you disable the log file in config.json you should be able to get passed it.

**Comment by rahoolio** [comment]
I'm able to start services now, but my devices aren't currently working. Trying a few things on my end

**Comment by tonesto7** [comment]
ok... I think I solved the error...  I will get it published here in a few

**Comment by flynhawaiian** [comment]
What was it?

**Comment by tonesto7** [comment]
I changed up the transport declaration to be defined at the start instead of using Winston.add() method.

**Comment by rahoolio** [comment]
Everything seems to be working on 2.1.2. Not sure what it was. I just redid the app ID and app token and that seemed to fix my (isolated) issue. 

I spoke too soon. It triggers once, but then when I try again it has no response. Still trying stuff on my end

**Comment by flynhawaiian** [comment]
Are you using the app id from the groovy file; off the smartthings app itself.  Not off the graph.smartthings webpage

**Comment by rahoolio** [comment]
Its all taken from the iOS smartthings app like normal. I think that was a weird circumstance. Currently it's very intermittent. It was actually nearly perfect before. (not a jab, just a clarification).

**Comment by flynhawaiian** [comment]
Yeah I was having some slow update issues before, and noticed after the reinstall everything is working much better.

**Comment by rahoolio** [comment]
Actually, I just noticed the homebridge v2 SmartApp says my plugin is v2.0.10 (Update available: vnull), except I am on v2.1.2 in hoobs.local...

**Comment by tonesto7** [comment]
something is up with hoobs updater... mine is doing it too... Reboot hoobs and you will see and update available for the plugin

**Comment by flynhawaiian** [comment]
Yeah I see the update 2.1.3

**Comment by tonesto7** [comment]
I'm off to bed... I will follow up in the morning.

**Comment by rahoolio** [comment]
Just for reference, this is what I'm seeing:
![Screenshot 2020-01-07 at 11 59 54 PM](https://user-images.githubusercontent.com/33258312/71951752-226d2100-31aa-11ea-9433-2eae21bb1c45.jpeg)
Spoke too soon again. The above screenshot is now showing "version: v2.1.0, Plugin: v2.1.3". I went into the define device type section and backed out and the version had updated.

![Screen Shot 2020-01-08 at 12 00 30 AM](https://user-images.githubusercontent.com/33258312/71951728-08334300-31aa-11ea-8d4e-6351f962a816.png)

**Comment by tonesto7** [comment]
If you guys want to join my slack here is the link: 
https://join.slack.com/t/tonesto7/shared_invite/enQtODk5NjA3MjE5NDYyLTIyZGE3Mzk5NTgxZWJkZjBlNGM5ZGU2ZGQ0ZDZiOTA5NDkwNGI0ZjQxMzM4ZTE3YWMyZGM3YjdhODdjMDljOGE

**Comment by THATDONFC** [comment]
I ran into the same issue when I did a fresh install just now. I went into the config in HOOBS and turned off the local log file and that error went away.

Log with "Enable Logging to file" enabled:
```[Homebridge] [1/8/2020, 7:34:01 AM] [SmartThings-v2] Initializing SmartThings-v2 platform...
[Homebridge] [1/8/2020, 7:34:01 AM] TypeError: winston.transports.Rotate is not a constructor
    at Logging.getLogger (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/libs/Logger.js:52:29)
    at new ST_Platform (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/ST_Platform.js:32:33)
    at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:293:34)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[Homebridge] [1/8/2020, 7:34:01 AM] Got SIGTERM, shutting down service...

**Comment by tonesto7** [comment]
The weird part is that I didn't change anything related to the logging libraries for v2.1 so this shouldn't be happening

**Comment by THATDONFC** [comment]
This was on version 2.1.3. At least that’s what was showing on the HOOBS plugin manager. Showing as updated ~35 minutes ago.

**Comment by tonesto7** [comment]
I'm working on some fixes... If they work then the next version will be 2.1.5

**Comment by tonesto7** [comment]
So I made some changes to the logger class which works fine under windows, macos, ubuntu but not Hoobs.

```TypeError: winston.transports.DailyRotateFile is not a constructor```
@mkellsy Do you have any idea why this maybe happening?

**Comment by THATDONFC** [comment]
> So I made some changes to the logger class which works fine under windows, macos, ubuntu but not Hoobs.
> 
> `TypeError: winston.transports.DailyRotateFile is not a constructor`
> @mkellsy Do you have any idea why this maybe happening?

Not sure if this helps you, but a google search yielded these results. 
https://github.com/winstonjs/winston-daily-rotate-file/issues/90

I don't know enough about .js to find the problem.

**Comment by mkellsy** [comment]
We do not use "winston" in HOOBS. This could be coming from another plugin.

**Comment by tonesto7** [comment]
This issue is on my Hoobs set up I only have the one plug-in installed

**Comment by THATDONFC** [comment]
@tonesto7 Check this out. Maybe there’s an error in the logger.js file?
https://github.com/winstonjs/winston/blob/master/lib/winston.js#L178

**Comment by mkellsy** [comment]
Thats what i am thinking because of this.
```
TypeError: winston.transports.Rotate is not a constructor
    at Logging.getLogger (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/libs/Logger.js:52:29)
```

**Comment by tonesto7** [comment]
I would agree if I was using v3 of Winston, but I’m using v2.4.4

**Comment by flynhawaiian** [comment]
> We do not use "winston" in HOOBS. This could be coming from another plugin.

Winston is in the global packages on a fresh install.

**Comment by tonesto7** [comment]
I’m going to try something suggested above by @THATDONFC

**Comment by mkellsy** [comment]
> > We do not use "winston" in HOOBS. This could be coming from another plugin.
> 
> Winston is in the global packages on a fresh install.

It's one of our dependencies that uses it, but HOOBS doesn't use it directly. We actually have a custom logger that pushes everything to a websocket.

**Comment by flynhawaiian** [comment]
Makes sense

**Comment by tonesto7** [comment]
I'm sure what to do with this... I doesn't make sense.  This plugin runs fine on all other platforms. 

This feels like it's specific to Hoobs... All the dependencies are there for Winston but for some reason it doesn' work

**Comment by mkellsy** [comment]
I am tracing what dependency uses Watson in HOOBS. 

You might want to change how the the dependency is marked in package.json.

```
"winston": "~2.4.4",
to
"winston": "^2.4.4",
```

Also do the same for lodash and express.

```
"lodash": "^4.17.15",
"express": "^4.17.1",
```

Then NPM can manage the dependencies for HOOBS and the plugins. See HOOBS doesn't install plugins in the global space. They are maintained in the executing users home. Therefore the plugin deps use the same node_modules folder. We do this for security, and to keep NPM working over time.

Can you use the logger built into Homebridge?

```
Homebridge.log.info()
Homebridge.log.debug()
```

Then everything can be pushed into the HB log. This is an idea, and it should make things simpler for you.

**Comment by tonesto7** [comment]
I will try this.  I'm also upgrading winston to v3 as well.  I just had to decipher the new format

**Comment by tonesto7** [comment]
Ok. I have it working with v2.1.9 of the plugin but I've discovered a different bug.
Basically, if you have more than one instance of the smartapp running when the plugin restarts it sends a local command to the ST Hub with the plugin IP and port which then sets any running homebridge app to send all ST device events to the last plugin that restarted

**Comment by tonesto7** [comment]
@flynhawaiian @rahoolio @THATDONFC 

Go ahead and update your smartapp and then your plugin to 2.1.12

**Comment by rahoolio** [comment]
is there supposed to be a new version of the smartapp? I still only see 2.1.0 on smartthings.com

Edit: I see 2.1.1 now, sorry

**Comment by rahoolio** [comment]
Well, it worked once. But now its intermittent. I may need to just start over.

**Comment by rahoolio** [comment]
Redid everything. It's still intermittent for me. I can usually turn something on, or turn something off, but after that it goes unresponsive. The brightness adjustment seems to really derail it.

In fact, adjusting the brightness doesn't seem to work at all...

**Comment by tonesto7** [comment]
@rahoolio I have no idea why you are seeing these issues.  The only difference between you and others is that yours is running under Hoobs.  I don't understand why it would be different. 
I and many others have been running this flawlessly for a couple of months.  I personally import 149 devices in HomeKit from ST and experienced no issues or lag at all.

I'm at a loss on how to correct this for you without some errors to point me in the right direction.

**Comment by mkellsy** [comment]
I have 250+ devices on SmartThings and it is instant for me. On HOOBS.

**Comment by tonesto7** [comment]
@mkellsy You using v2.x of the plugin?
Since you can only have 149 devices per HomeKit bridge that must have been fun picking and choosing which devices to import and not hit that threshold.
At one time I had 2 homebridge instances just for ST devices then I started filtering out devices

**Comment by mkellsy** [comment]
I don't use Apple. HOOBS has increased this limit in the custom Homebridge spin we have.

**Comment by tonesto7** [comment]
Now I'm confused... You develop a product/platform that is designed for an Apple home automation platform but you don't use Apple :|

**Comment by mkellsy** [comment]
I test on it, but for my production system, I don't use Apple. I have a Pixel. HOOBS goal is to open this to people who don't use Apple products too.

With the Google Home and Alexa plugins, this is truly ecosystem agnostic. And when I finish the Stringify clone in HOOBS we can even do automation without Apple.

**Comment by rahoolio** [comment]
> 
> 
> @rahoolio I have no idea why you are seeing these issues. The only difference between you and others is that yours is running under Hoobs. I don't understand why it would be different.
> I and many others have been running this flawlessly for a couple of months. I personally import 149 devices in HomeKit from ST and experienced no issues or lag at all.
> 
> I'm at a loss on how to correct this for you without some errors to point me in the right direction.

I understand. I've seen a few bugs posted recently that seem similar to my issue. I will follow them there.  To clarify, what I'm experiencing is new. On v2.0.1 I was running smoothly prior to 2.1.0. I may just need to revert back.

But for reference, this is something I'm seeing:



[Homebridge] ERROR: sendDeviceCommand Error:  [32m'Error: connect ETIMEDOUT 192.168.1.7:39500' [39m[Homebridge] DEBUG: sendDeviceCommand Resp: undefined[Homebridge] [1/10/2020, 6:33:55 PM] Unhandled Rejection "RequestError: Error: connect ETIMEDOUT 192.168.1.7:39500".[Homebridge] [1/10/2020, 6:33:55 PM] Unhandled Rejection "TypeError: callback is not a function".[Homebridge] [1/10/2020, 6:33:55 PM] RequestError: Error: connect ETIMEDOUT 192.168.1.7:39500
    at new RequestError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)[Homebridge] [1/10/2020, 6:33:55 PM] TypeError: callback is not a function
    at rp.catch.then (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/ST_Client.js:112:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)[Homebridge] (node:23952) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 19)[Homebridge] (node:23952) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 20)

**Comment by mkellsy** [comment]
If you read down the stack, it is being called from this file
```
at rp.catch.then (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/ST_Client.js:112:21)
```

I am doing a big plugin dev help push this weekend, and I will look, in depth, at this too. But first I have to help figure out the homebridge-nest recaptcha issue.

**Comment by tonesto7** [comment]
@rahoolio  Thanks for posting that exception.  I'm going to look at that area of code to see if there may be something I overlooked.

**Comment by flynhawaiian** [comment]
So with .12 and a fresh install of hoobs it no longer adds the devices in HOME.  I see them as accessories in the hoobs program, but no longer see them in the actual home app.

**Comment by tonesto7** [comment]
@flynhawaiian I'm not sure what to say.  I've not been able to find a way to get this to not work.  
I even moved my main instance over to running on Hoobs and it's working great. 
I do know there are some issues with Buttons and Thermostats in the latest version.
Do you have any button devices selected? If yes remove them from ST homebridge app and see if the devices show up.

**Comment by flynhawaiian** [comment]
That could be it.

**Comment by tonesto7** [comment]
I'm working on fixes right now.  The only thing I can think of was devices with Button and Switch capabilities were clashing and crashing homebridge

**Comment by tonesto7** [comment]
I've found the reason for the buttons crashing homebridge.  It was an issue with defining the Characteristic.setProps( {minValue, maxValue})

I just need to figure out why the button event is not firing HomeKit side real quick and I will get out these updates.  
I've added in the Sentry library to help collect exceptions errors so I can see them on my side.  (It doesn't collect any personal or identifiable info at all)

**Comment by flynhawaiian** [comment]
Yep that did it

**Comment by tonesto7** [comment]
@flynhawaiian  @rahoolio  @THATDONFC  Can you verify that the plugin works correctly now with the new version?

**Comment by THATDONFC** [comment]
Just updated the plugin and smart app and everything seems to be running smoothly! @tonesto7 

I had log to file turned off because the bug was preventing HOOBS from starting after throwing that error. I turned it back on and no errors so far.

**Comment by tonesto7** [comment]
@THATDONFC  Thanks for letting me know

**Comment by flynhawaiian** [comment]
Everything seems to be running smoothly now as well.  My only issue currently is sometimes when the "off" command is sent smartthings sometimes the command isn't be sent from HomeKit to smartthings.  Kinda weird.

**Comment by tonesto7** [comment]
I don’t understand why this runs so differently for so many users.  I’m amazed by how reliable my instance runs.

**Comment by tonesto7** [comment]
So now that I have the Sentry.io reporting in exceptions it's crazy to see how in every instance that the smartthings plugin is not to blame for crashing homebridge.
I've received over 2100 exceptions and they are all other plugins.

**Comment by flynhawaiian** [comment]
Mine is now perfect

**Comment by tonesto7** [comment]
Glad to hear it's working... I knew I would eventually get this thing stable :)

**Comment by tonesto7** [comment]
I'm going to close out this request and continue in #45
