### ISSUE TITLE
(BUG) Duplicate SmartApps in iOS app

### ISSUE THREAD

**Issue by turnepf** [tonesto7/homebridge-smartthings-v2#44]
Somehow I've ended up with duplicates of the SmartApp on my iPhone. I can't open any of them, and therefore can't remove them. I also can't remove the SmartApp via the IDE because it says the SmartApp is in use. I've contacted SmartThings support and they're working on it. Any ideas on how to fix this while I wait?

Thanks,

Patrick

**Comment by tonesto7** [comment]
It doesn’t even seem possible unless you accidentally overwrote the code of an existing application that creates devices

There are no restrictions on how many versions of this app you can have running at once so that wasn’t the issue

**Comment by turnepf** [comment]
So I figured out you can see the duplicates as 1 setup, 4 in process, on the new SmartThings app. I was able to blow away the "in progress" ones and then the 1 that was "installed" worked right again. I have no idea how this happened, but for future reference, it's easily fixed in the new app.
