### ISSUE TITLE
(BUG) v2.1.12 Motion Sensor and Multipurpose Sensor - no status update

### ISSUE THREAD

**Issue by Damianeq90** [tonesto7/homebridge-smartthings-v2#48]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The SmartApp and Device Handler are using the latest code available.
-  [ x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?:15
-  Mobile App Version(Not required): 2.1
-  SmartApp Version: 2.1.1"
-  Device Handler Version:
-  Homebridge Version: 0.4.50
-  NodeJS Version:

## Expected Behavior
After the introduction of the last final update of 2.1.12, they stopped updating their detector status, everything was working today in the previous version, I'm not sure but it was 2.1.7, but I can be wrong.
## Current Behavior
**What happens instead of the expected behavior?**

## Context

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by hardlock75** [comment]
hi!
i have Multipurpose Sensor and mine is working well. Are you updating Smarthing app  to 2.1.1 yes i think but do you update the homebridge plugin?
![image](https://user-images.githubusercontent.com/58529389/72127713-9809f600-333e-11ea-837d-67e54da27c28.png)

big question, is it working in Smartthings?

**Comment by Damianeq90** [comment]
To be sure, I have installed everything again and I have a problem similar to the one described here https://github.com/tonesto7/homebridge-smartthings-v2/issues/49 devices do not download the current status only the status is downloaded the next time it is restarted and it stops without updating.

**Comment by Damianeq90** [comment]
I am very stubborn, I reinstalled the container on QNAP and what happened shocked me the most. The whole homebridge interface looks different, oddly yesterday when I installed it, I didn't see these changes. Today I see interaface in purple with widgets (homebridge-config-ui-x v4.7.0-test.32 - © 2020 oznu) I don't have a device tab but everything works also sensors :) and in the installation on QNPA in the network options I chose Bridge instead of HOST
