### ISSUE TITLE
SmartThings Home Monitor - Not Working New SmartThings App

### ISSUE THREAD

**Issue by OnlyOnly0613** [tonesto7/homebridge-smartthings-v2#49]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ ] The SmartApp and Device Handler are using the latest code available.
-  [ ] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: **33**
-  Mobile App Version(Not required):
-  SmartApp Version: **2.1.1**
-  Device Handler Version:  Plugin 2.1.5
-  Homebridge Version: **0.4.5**
-  NodeJS Version: **6.1.4**

## Expected Behavior
**Tell us what you think should be happening**

SmartThings SHM in HomeKit is ON.
SHM status does not reflect or update the actual SHM from SmartThings SHM (not classic)

## Current Behavior
**What happens instead of the expected behavior?**

SHM reports OFF status in HomeKit no matter what the actual status in the SmartThings (not classic) app.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.  SHM in your 2.1.1 smartapp in turned ON.
2.  SHM shows OFF in HomeKit
3. Changing status to arm or disarm in SmartThings app will not update the status in HomeKit.

**Comment by hardlock75** [comment]
mine is working well. 
do you update Homebridge Plugin in new version

![image](https://user-images.githubusercontent.com/58529389/72128130-d653e500-333f-11ea-9198-54d69d800aa4.png)

**Comment by Damianeq90** [comment]
In my version v2.1.12 device status is downloaded at restart homebridge later is not updated. However, you can turn on and off normally, e.g., bulbs.

**Comment by OnlyOnly0613** [comment]
Upgraded to v2.1.12 this morning.
SmartApp is the latest also.
Turned off "Control SHM in HomeKit"
Save and Wait for HomeKit icon to disappear.
Turned on "Control SHM in HomeKit"
Save and Wait for HomeKit to appear.

The status in homekit shows OFF
The SHM in SmartThings (Connect) shows ARMED.
Changing SHM doesn't update STATUS in HomeKit.

*** I'm using SmartThing Connect ONLY, NOT CLASSIC SmartThings***

**Comment by tonesto7** [comment]
I'm not sure that the Groovy smartapps see SHM events from the new API version of SHM

**Comment by tonesto7** [comment]
I just confirmed my guess above was true.

**Comment by OnlyOnly0613** [comment]
Thanks! We can use scenes to workaround this.

**Comment by nebrelbug** [comment]
@tonesto7 are there any plans to get this to work? Is there anything I could do to contribute?

@OnlyOnly0613 how were you able to use scenes as a workaround?

**Comment by tonesto7** [comment]
I have a new version in the works that uses the new API. It’s going to be awhile before it’s ready to release. 
Work and family have been monopolizing my time lately

**Comment by nebrelbug** [comment]
@tonesto7 sounds good :)
