### ISSUE TITLE
No valid versions available for homebridge-smartthings-v2

### ISSUE THREAD

**Issue by RiggsUS** [tonesto7/homebridge-smartthings-v2#5]
Great can't wait to try it.
Tried to install it today but I got an error "No valid versions available for homebridge-smartthings-v2"
I'm running a Raspberry pi 3, with HomeBridge in Docker.
unname -a: Linux homebridge 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

Complete output:
/homebridge # npm i -g homebridge-smartthings-v2
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for homebridge-smartthings-v2

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-03T20_28_43_032Z-debug.log
/homebridge # cat /root/.npm/_logs/2019-12-03T20_26_20_615Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'homebridge-smartthings-v2'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose npm-session caaa8e647ac1e228
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/homebridge-smartthings-v2 91ms (from cache)
8 silly fetchPackageMetaData error for homebridge-smartthings-v2@latest No valid versions available for homebridge-smartthings-v2
9 timing stage:rollbackFailedOptional Completed in 9ms
10 timing stage:runTopLevelLifecycles Completed in 206ms
11 verbose type tag
12 verbose stack homebridge-smartthings-v2: No valid versions available for homebridge-smartthings-v2
12 verbose stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:39:11)
12 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:24:14
12 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
12 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
12 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
12 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
12 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
12 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
12 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
12 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
12 verbose stack     at processImmediate (internal/timers.js:439:21)
13 verbose cwd /homebridge
14 verbose Linux 4.19.75-v7+
15 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "homebridge-smartthings-v2"
16 verbose node v12.13.1
17 verbose npm  v6.12.1
18 error code ENOVERSIONS
19 error No valid versions available for homebridge-smartthings-v2
20 verbose exit [ 1, true ]

**Comment by scordinskyc** [comment]
FWIW, I cloned the repository and manually installed it with npm. Works fine.

**Comment by tonesto7** [comment]
that's because i can't publish it yet

**Comment by RiggsUS** [comment]
Sorry I assumed all was good to go with the instructions being listed, ill install it via GitHub.
