### ISSUE TITLE
(BUG) V2.1.12 Thermostats don't refresh in Homekit

### ISSUE THREAD

**Issue by hardlock75** [tonesto7/homebridge-smartthings-v2#50]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ ] The SmartApp and Device Handler are using the latest code available.
-  [ ] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?:
-  Mobile App Version(Not required):
-  Smarthin App Version: 2.1.1 
-  Device Handler Version:
-  Homebridge Version: Hub V2
-  Homebridge plugin:  v2.1.1 - v2.1.12
-  NodeJS Version: V13.3.0

## Expected Behavior
**Tell us what you think should be happening**

## Current Behavior
**What happens instead of the expected behavior?**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

hi tonesto7
there is big news... almost works. the problem is when i Heating set point to 22 celsius exemple. The thermostat start to heat, but when i exit homekit and i re-open homekit on my iphone. Is stay to 20 celsius but the heating set point is 22.

![image](https://user-images.githubusercontent.com/58529389/72126725-33996780-333b-11ea-8a13-93d68fb1bd3c.png)
![image](https://user-images.githubusercontent.com/58529389/72126775-67748d00-333b-11ea-99b5-c26446032caa.png)

When i re-open Homekit there is the information

![image](https://user-images.githubusercontent.com/58529389/72126851-b4f0fa00-333b-11ea-9f72-ea1fe4ad9e28.png)

the information was not saved in the log.

Is it possible to interrogate the heating set point thermostat and push the information in the home kit? i don't know if is possible...

**Comment by tonesto7** [comment]
I'm not able to duplicate this at all.  Changes from ST are mirrored in HomeKit instantly

**Comment by hardlock75** [comment]
I can define the temperature in homekit and is working, he start to heat
![image](https://user-images.githubusercontent.com/58529389/72186047-4b67fe80-33c2-11ea-9af6-c3ea039ff883.png)

when i return in homekit he doe't match. 
![image](https://user-images.githubusercontent.com/58529389/72186435-45bee880-33c3-11ea-98a1-03598b984a68.png)

**Comment by tonesto7** [comment]
maybe do a screen recording from your iPhone so I can see the issue in action?

**Comment by hardlock75** [comment]
There is in action sorry for my bad english

https://youtu.be/rZxNIjX5Lq0

**Comment by tonesto7** [comment]
Thanks for the video... I will attempt to duplicate it on my side and let you know.

**Comment by hardlock75** [comment]
hi again! 
i think the problem come to the Homebridge plugin, but I'm not sure... I do a video on Homebridge config Ui X in accessory, i did the same exercise on thermostat.

https://youtu.be/CK54ekr1qwc

**Comment by 00JohnD** [comment]
I have the same issue here since the update latest update to 2.1.12. Thanks for reporting

**Comment by tonesto7** [comment]
I’m investigating this right now hopefully I can track down the cause today and get a fix out

**Comment by 00JohnD** [comment]
Awesome, thank you very much for your work!

**Comment by hardlock75** [comment]
Thx nice reactive!!

**Comment by hardlock75** [comment]
update Homebridge plugin V2.1.13 

some changes have been made, but temperatuure get targetTemp (get): 21
stay at 21 example

see the new video in Homebridge Config UI X. Some problème in Homekit

https://youtu.be/HcvPXxVfoeY

**Comment by tonesto7** [comment]
@hardlock75 I'm not sure what to tell you then... I have two test devices I used the validate it and they worked 100%. 

HomeKit can only update if the device handler sends the change event.
Watch the plugin logs for the device events to show they are sent to the plugin.

**Comment by hardlock75** [comment]
is it possible to change the temperature by skipping .5
example 21 to 21.5 to 22 to 22.5 Celsius 

i don't know if thermostat like

**Comment by hardlock75** [comment]
new video in homekit 
https://youtu.be/MPnvhsRsU8I

the problem come to the variable 

when i put 25 in homekit do this:

C Bureau Carlos TH1124ZB) [HEATINGSETPOINT] is 25.0 
[1/12/2020, 8:31:31 pm] [SmartThings-v2] INFO: [Device Change Event]: (Sinopé RDC Bureau Carlos TH1124ZB) [THERMOSTATOPERATINGSTATE] is heating 

when i open Homekit do this:

targetTemp(get):  21.0
---------------------

when i open homekit he enter variable targettemp (get):21
--------
i think is when open homekit, the correct variable is [HEATINGSETPOINT](get)

if check HEATINGSETPOINT when open homekit there is working i think
--------
sorry the lines of code is not my strength

**Comment by 00JohnD** [comment]
I upgraded the plugin to 2.1.13 and still got the same issue (non-Hoobs), tried with a fresh install of Hoobs and again got the same issue. Thanks again for trying

**Comment by hardlock75** [comment]
> 
> 
> I upgraded the plugin to 2.1.13 and still got the same issue (non-Hoobs), tried with a fresh install of Hoobs and again got the same issue. Thanks again for trying

thank you! to report the bug

**Comment by tonesto7** [comment]
@hardlock75  I think I've resolved the issue.  I'm just testing the fix right now

**Comment by hardlock75** [comment]
I update Homebridge plugin V2.1.14 and report same bug that version V2.1.13

**Comment by tonesto7** [comment]
i didnt fix yet... I need to work through this further.  I'm heading to bed soon.  I will address it tomorrow though.

**Comment by 00JohnD** [comment]
Your involvement to this project is awesome @tonesto7 Thank you very much, will definitely donate.

Keep up the good work!

**Comment by tonesto7** [comment]
@hardlock75  I haven't forgotten about you.  I've been reworking the thermostat trying to fix this annoying issue.  Hopefully have a release for you tonight.

**Comment by tonesto7** [comment]
@hardlock75  @00JohnD Please update your plugin to v2.1.15 and let me know if the issue is resolved

**Comment by tonesto7** [comment]
I am still seeing some weird behaviors when changing the mode remotely where is sets the temp to 100.
I'm trying to work it out right now

**Comment by tonesto7** [comment]
@hardlock75 @00JohnD I just pushed out another update v2.1.16 which i think fixes the thermostat finally

**Comment by hardlock75** [comment]
flawless victory!
working well for me...

**Comment by hardlock75** [comment]
update in v2.1.15
flawless victory! 
working..but read you push 2.1.16 in same time.. i update it

**Comment by hardlock75** [comment]
it works for me, but one last thing if i can. Is it possible to increase the temperature in increments of .5 in Homekit
exemple 21, 21.5, 22, 22.5 ??

I am detail-oriented

**Comment by tonesto7** [comment]
Crap I forgot about that increment part I promise I’ll get it in there tonight

**Comment by hardlock75** [comment]
> 
> 
> Crap I forgot about that increment part I promise I’ll get it in there tonight

no problem my friend, 
you have already put a lot of energy to correct a bigger problem. After that, you can close it, this bug :)

**Comment by tonesto7** [comment]
I haven't been successful in getting the .5 degree increments to work.  I will continue to try.

**Comment by hardlock75** [comment]
> 
> 
> I haven't been successful in getting the .5 degree increments to work. I will continue to try.

I'm not sure it can be done. When I ask siri to change the temperature to 23.5 celsius, it automatically changes to 24.

**Comment by tonesto7** [comment]
It shows an option under homebridge but I'm not sure that HomeKit supports it anymore.  
Either way, the values are set in the upcoming release so if support is restored it will start working

**Comment by hardlock75** [comment]
so nice Thank you!!
have nice day my friend
