### ISSUE TITLE
[Feature Request] Local Control On/Off By Device

### ISSUE THREAD

**Issue by dustyberry1** [tonesto7/homebridge-smartthings-v2#51]
**Is your feature request related to a problem? Please describe.**
I have a thermostat which breaks when local control is on. The thermostat is a custom device handler/smartapp for Nexia, available at link below. When I turn local control off it works fine, but of course i lose local control for my other devices.

https://community.smartthings.com/t/how-do-you-control-a-nexia-thermostat-with-a-smartthings-hub/34046

**Describe the solution you'd like**
Ideally override the local control at the device level, kind of how you can exclude certain device capabilities in config

**Describe alternatives you've considered**
There is an official Nexia integration but it doesn't show up when configuring devices in the smartapp, so i use this one instead. Bug for official Nexia not working: https://github.com/tonesto7/homebridge-smartthings-v2/issues/52

**Additional context**

**Comment by tonesto7** [comment]
Why not just use this plugin to bring in your thermostat into HomeKit. 
Thermostats are a tricky beast to handle under smartthings specifically because they are more capable under the new API and it's hard to cover them under the Groovy API.  
https://www.npmjs.com/package/homebridge-nexia
