### ISSUE TITLE
(BUG) Nexia Thermostat Missing from SmartApp

### ISSUE THREAD

**Issue by dustyberry1** [tonesto7/homebridge-smartthings-v2#52]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The SmartApp and Device Handler are using the latest code available.
-  [X] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 16
-  Mobile App Version(Not required):
-  SmartApp Version: 2.1.1
-  Device Handler: Version 2.1.12
-  Homebridge Version: 0.4.50
-  NodeJS Version: 12.14.0

## Expected Behavior
I should be able to see Nexia devices in the smartapp when configuring devices, since they are linked in smartthings

## Current Behavior
Nexia devices are missing in every category in the smartapp and so cannot be enabled in homekit

## Steps to Reproduce (for bugs)
1. Smartthings App: Add -> New Device -> Nexia -> Thermostat
2. Link Nexia Account
3. See the Nexia Thermostat enabled in Smartthings App
4. Goto Homebridge v2 smartapp
5. The Nexia thermostat is not a visible device 

## Context
I want to be able to enable my Nexia Thermostat in Homekit

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
If it doesn't show up it's because it doesn't have the capabilities required for normal thermostat.
Try using this plugin https://www.npmjs.com/package/homebridge-nexia

**Comment by dustyberry1** [comment]
Yeah I've tried that plugin but couldn't figure it out, no readme and doesn't seem maintained. Hopefully Nexia will update their official integration with Smartthings so it works correctly
