### ISSUE TITLE
(BUG) Turning Thermostat to Heat Defaults to 100 Degrees

### ISSUE THREAD

**Issue by jianyu-li** [tonesto7/homebridge-smartthings-v2#57]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The SmartApp and Device Handler are using the latest code available.
-  [x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?:
-  Mobile App Version(Not required):
-  SmartApp Version:
-  Device Handler Version:
-  Homebridge Version:
-  NodeJS Version:

## Expected Behavior
**Tell us what you think should be happening**

## Current Behavior
**What happens instead of the expected behavior?**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by jianyu-li** [comment]
About Your Setup

How many devices are detected?: 2
Mobile App Version(Not required):
SmartApp Version: 2.1.1
Device Handler Version:
Homebridge Version: 0.40.50
NodeJS Version:12.13.1
Expected Behavior

When changing the thermostat mode from off to heat, it should retain current temperature until changed 

Current Behavior

When heat mode turns on, the degrees in the Home app is set to 100 degrees 

Steps to Reproduce (for bugs)

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant

Context

**How has this issue affected you? What are you trying to accomplish?
Providing context helps us come up with a solution that is most useful in the real world

**Comment by jianyu-li** [comment]
It doesn’t always default to 100 but it does most of the time. Happens even when I 3D Touch the thermostat it jumps up to 100

**Comment by tonesto7** [comment]
Sorry, I'm making so many releases.  Are you running the latest one (v2.1.16)?

**Comment by jianyu-li** [comment]
IDE says its 2.1.1 but also says that local and repository versions are identical and not pulling in any updates

**Comment by tonesto7** [comment]
i mean the plugin version

**Comment by jianyu-li** [comment]
oh sorry about that. its on 2.1.15

**Comment by tonesto7** [comment]
please update to 2.1.16 to see if it's fixed

**Comment by jianyu-li** [comment]
so far so good. I'll keep you posted. I am noticing a lot of this happening in my logs though. is that normal?`[Homebridge] heatingSetpoint:  71
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  71
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  71
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  71
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  71
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  71
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  71
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  71
[Homebridge] coolingSetpoint:  78
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  71
[Homebridge] heatingSetpoint:  71
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  71
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  71
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  71
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  71
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  71
[Homebridge] coolingSetpoint:  78
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  78
[Homebridge] heatingSetpoint:  71`

**Comment by tonesto7** [comment]
yea those are logs I forgot to disable...  
I have another push coming out tonight which I will make sure the logs are removed

**Comment by jianyu-li** [comment]
Seems to be working now. Thanks for all you do
