### ISSUE TITLE
(BUG) {Upgrade path from v1} 

### ISSUE THREAD

**Issue by adavison007** [tonesto7/homebridge-smartthings-v2#68]
Is there an upgrade path from v1 to v2 or do I delete all existing devices in homekit, do this install and then re add them?

**Comment by tonesto7** [comment]
SmartApp:
* You can use the existing SmartApp and just update it to the latest code then go through the app and update any new settings.

Plugin:
* Can not be upgraded and requires you to remove the old bridge from the home app and clear the accessoryCache and persist folders.
* Then install the new plugin and update the old config.json

**Comment by adavison007** [comment]
Thanks, so when you say remove old bridge, do you mean my RPI homebridge from home kit? if so that would mean I loose all the devices from other plugins? or do you mean just remove the original v1 plugin?

I have over 120 devices via other homebridge plugins, so if you can confirm that would be great?

Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 16 Jan 2020, at 22:30, Tonesto7 <notifications@github.com> wrote:

SmartApp:

You can use the existing SmartApp and just update it to the latest code then go through the app and update any new settings.
Plugin:

Can not be upgraded and requires you to remove the old bridge from the home app and clear the accessoryCache and persist folders.
Then install the new plugin and update the old config.json

**Comment by tonesto7** [comment]
Technically you can just remove the plug-in from your home bridge instance but the way that  the devices get cached might cause an issue. 
It’s either going to work or it’s not and I apologize that you have to do this but based on changing the type of plug-in requires a fresh start

**Comment by adavison007** [comment]
I did the update as follows and all worked fine.

Removed the JSON config in Homebridge 
Updated the smart app code in the IDE
Removed the plugin from Homebridge
Restarted Homebridge
Installed new plugin in
All worked with existing devices

One question… My thermostats (Tado) usd to bring in three tiles… humidity, temprature and the main thermostat control as seperate tiles in Homekit… now with V2, I see humidity, but only as part of the thermostat in settings, so I can say show as seperate tiles? 

AWESOME! 
Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 16 Jan 2020, at 23:08, Tonesto7 <notifications@github.com> wrote:

Technically you can just remove the plug-in from your home bridge instance but the way that the devices get cached might cause an issue.
It’s either going to work or it’s not and I apologize that you have to do this but based on changing the type of plug-in requires a fresh start
