### ISSUE TITLE
(BUG) OAuth instructions are incorrect

### ISSUE THREAD

**Issue by JJJ** [tonesto7/homebridge-smartthings-v2#70]
## Verify the following before opening an trouble issue

> Scroll down to the OAuth section and click Enable OAuth in Smartapp

However:

<img width="1246" alt="Screen Shot 2020-01-17 at 4 37 30 PM" src="https://user-images.githubusercontent.com/88951/72651032-c6439300-3947-11ea-93a7-0f1e3f039fd1.png">

**Comment by tonesto7** [comment]
@JJJ Mind telling me what was wrong with the instructions?

**Comment by tonesto7** [comment]
Just an FYI, you don't use any of that info in the config file at all

**Comment by JJJ** [comment]
I quoted the incorrect instruction, and included a screenshot of what’s in the oAuth section. Unsure what more to add?

There is nothing to click to enable oAuth, though it does seem to appear to be enabled on its own?

(Unless I did this someplace else ahead of time somehow?)

**Comment by tonesto7** [comment]
That’s because oauth was already enabled from a previous version.  It’s only enabled once

**Comment by JJJ** [comment]
Got it. That makes sense. Maybe worth a note in the install instructions? Or no?
