### ISSUE TITLE
(BUG) v2.2 ERROR: initializeAccessory (fromCache: false)

### ISSUE THREAD

**Issue by cnnn** [tonesto7/homebridge-smartthings-v2#71]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The SmartApp and Device Handler are using the latest code available.
-  [x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?:22
-  Mobile App Version(Not required):
-  SmartApp Version:2.2
-  Device Handler Version:2.2
-  Homebridge Version:0.4.50
-  NodeJS Version:8.11.1

## Expected Behavior
Homebridge should launch without error

## Current Behavior
Getting ERROR: initializeAccessory (fromCache: false) Error:Cannot read property 'toString' of undefined TypeError: Cannot read property 'toString' of undefined

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Configure devices with a previous handler v2.0.x
2. Upgrade smart app and homebridge plugin to 2.2
3. Restart homebridge

## Context
**How has this issue affected you? What are you trying to accomplish?
Devices become unresponsive.
**Providing context helps us come up with a solution that is most useful in the real world**

---
Jan 17 14:56:48 volumio homebridge[17226]: [1/17/2020, 2:56:48 pm] [SmartThings-v2] INFO: INFO: Your plugin version is up-to-date
Jan 17 14:56:49 volumio homebridge[17226]: [1/17/2020, 2:56:48 pm] [SmartThings-v2] NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false
Jan 17 14:56:49 volumio homebridge[17226]: [1/17/2020, 2:56:49 pm] [SmartThings-v2] NOTICE: Temperature Unit is Now: (F)
Jan 17 14:56:49 volumio homebridge[17226]: [1/17/2020, 2:56:49 pm] [SmartThings-v2] NOTICE: Updating Global Values | HubIP: 172.16.100.176 | UseLocal: true
Jan 17 14:56:49 volumio homebridge[17226]: [1/17/2020, 2:56:49 pm] [SmartThings-v2] WARN: Devices to Remove: (0) []
Jan 17 14:56:49 volumio homebridge[17226]: [1/17/2020, 2:56:49 pm] [SmartThings-v2] INFO: Devices to Update: (22)
Jan 17 14:56:49 volumio homebridge[17226]: [1/17/2020, 2:56:49 pm] [SmartThings-v2] GOOD: Devices to Create: (0) []
Jan 17 14:56:49 volumio homebridge[17226]: [1/17/2020, 2:56:49 pm] [SmartThings-v2] ERROR: initializeAccessory (fromCache: false) Error:Cannot read property 'toString' of undefined TypeError: Cannot read property 'toString' of undefined
Jan 17 14:56:49 volumio homebridge[17226]: at PlatformAccessory.addService (/lib/node_modules/homebridge/lib/platformAccessory.js:54:59)
Jan 17 14:56:49 volumio homebridge[17226]: at PlatformAccessory.getOrAddServiceByName (/lib/node_modules/homebridge-smartthings-v2/src/ST_Accessories.js:221:24)
Jan 17 14:56:49 volumio homebridge[17226]: at DeviceCharacteristics.button (/lib/node_modules/homebridge-smartthings-v2/src/ST_DeviceCharacteristics.js:174:40)
Jan 17 14:56:49 volumio homebridge[17226]: at svcTypes.forEach (/lib/node_modules/homebridge-smartthings-v2/src/ST_Accessories.js:107:44)
Jan 17 14:56:49 volumio homebridge[17226]: at Array.forEach (<anonymous>)
Jan 17 14:56:49 volumio homebridge[17226]: at ST_Accessories.configureCharacteristics (/lib/node_modules/homebridge-smartthings-v2/src/ST_Accessories.js:104:22)
Jan 17 14:56:49 volumio homebridge[17226]: at ST_Accessories.initializeAccessory (/lib/node_modules/homebridge-smartthings-v2/src/ST_Accessories.js:67:25)
Jan 17 14:56:49 volumio homebridge[17226]: at ST_Platform.updateDevice (/lib/node_modules/homebridge-smartthings-v2/src/ST_Platform.js:224:55)
Jan 17 14:56:49 volumio homebridge[17226]: at toUpdate.forEach.device (/lib/node_modules/homebridge-smartthings-v2/src/ST_Platform.js:184:61)
Jan 17 14:56:49 volumio homebridge[17226]: at Array.forEach (<anonymous>)
Jan 17 14:56:49 volumio homebridge[17226]: at client.getDevices.catch.then.resp (/lib/node_modules/homebridge-smartthings-v2/src/ST_Platform.js:184:38)
Jan 17 14:56:49 volumio homebridge[17226]: at <anonymous>
Jan 17 14:56:49 volumio homebridge[17226]: at process._tickDomainCallback (internal/process/next_tick.js:228:7)
Jan 17 14:56:49 volumio homebridge[17226]: [1/17/2020, 2:56:49 pm] [SmartThings-v2] ALERT: Total Initialization Time: (2 seconds)
Jan 17 14:56:49 volumio homebridge[17226]: [1/17/2020, 2:56:49 pm] [SmartThings-v2] NOTICE: Unknown Capabilities: ["Relay Switch","Holdable Button"]
Jan 17 14:56:49 volumio homebridge[17226]: [1/17/2020, 2:56:49 pm] [SmartThings-v2] INFO: SmartThings DeviceCache Size: (22)
Jan 17 14:56:49 volumio homebridge[17226]: [1/17/2020, 2:56:49 pm] [SmartThings-v2] INFO: WebServer Initiated...
Jan 17 14:56:49 volumio homebridge[17226]: [1/17/2020, 2:56:49 pm] [SmartThings-v2] INFO: Sending StartDirect Request to SmartThings | SendToLocalHub: (true)
Jan 17 14:56:49 volumio homebridge[17226]: [1/17/2020, 2:56:49 pm] [SmartThings-v2] INFO: Direct Connect Active | Listening at 172.16.100.40:8000
Jan 17 14:56:49 volumio homebridge[17226]: [1/17/2020, 2:56:49 pm] [SmartThings-v2] INFO: SmartThings-v2 Hub Communication Established

**Comment by tonesto7** [comment]
Thanks for reporting I’ll look into it

**Comment by cnnn** [comment]
Btw I was upgrading from v2.0.10 and saw the errors. I downgraded to v2.1.0 then the error is gone. However all devices are still showing "no responding" in the Home app, without any error in the logs.

I eventually reverted to v2.0.10 to get everything working. The smart app remains at v2.2.

**Comment by tonesto7** [comment]
This should be resolved.  Let me know

**Comment by cnnn** [comment]
> This should be resolved. Let me know

Still seeing the same error on 2.2.1.
