### ISSUE TITLE
(BUG) {Thermostats not working correctly with Heat / Cool / Auto Mode} 

### ISSUE THREAD

**Issue by adavison007** [tonesto7/homebridge-smartthings-v2#76]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The SmartApp and Device Handler are using the latest code available.
-  [X] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
Everything is up today and does connect from smart things to homebridge. PS I don't see a device handler for your IDE as mentioned above, just a smart app? I do have the homebridge plugin and smart app installed and everything works

## Expected Behavior
Thermostats in Smart things everything works as normal, see photo, I can heat, cool, or End manual temp, which takes the thermostat back to it's preset.

When this is translated into Home kit, the follow Happens

**- Heat (Homekit)** - Does a random number - It should take the heat setting from the variable set in smart things (2 degrees I have in the Tado connect settings in smart things)
**- Cool (Homekit)** -  Does a random number - It should take the cool setting from the variable set in smart things (2 degrees I have in the Tado connect settings in smart things)
**- Off (Homekit**) - this works fine
**- Auto (Homekit)** - This should give automatically do end manual temp and know the temp to go to based on the thermostat settings, however your's gives a cool to heat variable, which randomly makes two numbers up and the thermostat takes the lower temp from the range

Also, by standard, the thermostat should be in Auto mode, currently it is in heat mode. Auto means it is doing what the thermostat timer settings are saying until a manual change., if you manually change it should go to heat if you set hotter or cool if you set lower, if you move back to Auto, it should cancel manual control and take the timer settings from the thermostat, which his what happens when you do it smart things.

## Current Behavior
See above

## Context
**How has this issue affected you? What are you trying to accomplish? Basically, I can't control my thermostat with confidence from homekit
**Providing context helps us come up with a solution that is most useful in the real world**
I'm happy to work on this with you - I'm even happy to send you a Tado thermostat for free to help?
![IMG_1078](https://user-images.githubusercontent.com/47482260/72679843-138c4580-3aab-11ea-8986-ca059a4f1db6.png)

![IMG_1079](https://user-images.githubusercontent.com/47482260/72679844-171fcc80-3aab-11ea-8c36-6d9052cc6a1a.jpeg)

![IMG_1082](https://user-images.githubusercontent.com/47482260/72679904-d5435600-3aab-11ea-8146-2b7aeb3f078a.jpeg)

![IMG_1081](https://user-images.githubusercontent.com/47482260/72679846-1dae4400-3aab-11ea-896d-68195d637748.jpeg)

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
@adavison007 Ok, I need some time to absorb this.  
On a side-note doesn't Tado support homekit natively?

**Comment by adavison007** [comment]
> @adavison007 Ok, I need some time to absorb this.
> On a side-note doesn't Tado support homekit natively?

@tonesto7 I have 32 Tado devices and the native Tado plugin does not work for me... it mixes the thermostats up (lack of memory on there kit) So if I change living room, it changes the stuff sometimes, or the kitchen other times... they changed the amount of devices they support after I reported this issue 2 years ago and refuse to support me....  However... I used to use the Tado plugin in homebridge by @sedyx but since iOS 13 his has issues, and he seems to have gone missing in action from responding to anyone on his page, hope he's ok. So that's why you ar Amy only hope. That said all the things I mention about thermoses should be relevant for anyone with a thermostat of any make? Thanks in advance and thanks for fixing shades... looks like the other chap is running on old version of your app :)

**Comment by tonesto7** [comment]
Can you do me a favor and go into the smart app > Device Data Viewer > select a thermostat > view the data > share the output here

**Comment by adavison007** [comment]
Sure , also you can’t view humidity as a separate tile in homekit, your previous b1 allowed this :)

{
    "name": "Bedroom",
    "basename": "Bedroom",
    "deviceid": "915ae1a2-581f-4c4d-8347-8dc90631e19e",
    "status": "ACTIVE",
    "manufacturer": "Unknown",
    "model": "Tado Heating Thermostat",
    "deviceNetworkId": "4|HEATING|9ece1b1f-710a-45a0-ab7a-ce9fd1a71d5e|null",
    "lastActivity": "2020-01-17T12:11:13+0000",
    "capabilities": [
        "Actuator",
        "Polling",
        "Refresh",
        "Relative Humidity Measurement",
        "Temperature Measurement",
        "Thermostat",
        "Thermostat Heating Setpoint",
        "Thermostat Mode",
        "Thermostat Operating State",
        "Thermostat Setpoint"
    ],
    "commands": [
        "auto",
        "cool",
        "emergencyHeat",
        "endManualControl",
        "fanAuto",
        "fanCirculate",
        "fanOn",
        "heat",
        "heatingSetpointDown",
        "heatingSetpointUp",
        "off",
        "on",
        "poll",
        "refresh",
        "setCoolingSetpoint",
        "setHeatingSetpoint",
        "setSchedule",
        "setThermostatFanMode",
        "setThermostatMode",
        "temperatureDown",
        "temperatureUp"
    ],
    "customflags": [
        
    ],
    "attributes": {
        "coolingSetpoint": null,
        "coolingSetpointRange": null,
        "heatingSetpoint": 20.00,
        "heatingSetpointRange": null,
        "humidity": 44.30,
        "schedule": null,
        "supportedThermostatFanModes": null,
        "supportedThermostatModes": null,
        "tadoMode": "HOME",
        "temperature": 20.2,
        "thermostatFanMode": null,
        "thermostatMode": "heat",
        "thermostatOperatingState": "heating",
        "thermostatSetpoint": 20.00,
        "thermostatSetpointRange": null
    },
    "eventHistory": [
        "Sun Jan 19 17:19:37 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:18:41 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:17:37 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:16:37 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:15:38 UTC 2020 | [outsidetemperature] | (3.33 C)",
        "Sun Jan 19 17:15:38 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:14:38 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:13:37 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:12:38 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:11:39 UTC 2020 | [humidity] | (44.30 %)",
        "Sun Jan 19 17:11:39 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:10:38 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:09:37 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:08:38 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:07:41 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:06:40 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:05:39 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:04:42 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:03:39 UTC 2020 | [null] | (refresh)",
        "Sun Jan 19 17:02:37 UTC 2020 | [null] | (refresh)"
    ]
}

Adam Davison
adavison@me.com
07748 761448

Sent from my iPhone

> On 19 Jan 2020, at 16:00, Tonesto7 <notifications@github.com> wrote:
> 

﻿
Can you do me a favor and go into the smart app > Device Data Viewer > select a thermostat > view the data > share the output here

**Comment by tonesto7** [comment]
thanks...
Humidity for thermostats is part of the Thermostat service and not seen as a separate accessory.
This has not changed from the v1 plugin

**Comment by tonesto7** [comment]
I’m not sure what I can do here.  If thermostat device sends the new set point events then the thermostat on HomeKit side will match the current heat/cool temps. 
It doesn’t randomly assign a temp in auto it uses the devices heatSetpoint and coolSetpoint attributes to set the corresponding HomeKit setpoint.  So if the handler doesn’t send either of the setpoint attribute changes to Homebridge than that might explain the issue. 

As far as auto goes it’s working exactly how auto mode works.  It maintains the temp between the heat and cool temps.  There is no other way for it to behave, it’s not going to show a single setpoint. 

The old version didn’t implement the thermostat service properly so that’s why it only showed a single temp.  It basically measured the difference between the current temp and the heat setpoint and then for the cool which ever was closer showed the setpoint

**Comment by jdebardi** [comment]
For reference, the native Tado HomeKit integration does not show the range or auto.
Maybe there is a way ST plugin can present it the same way?
Works fine for me reverting back from manual to an auto set temp etc

![10667781-C0FE-419B-BF54-EBFA46E30ED7](https://user-images.githubusercontent.com/22931910/72783383-2ecb9200-3c1e-11ea-9299-fdb6bb01ff7e.png)
![B69FDA1A-9C46-4B72-835A-2030DB11F77F](https://user-images.githubusercontent.com/22931910/72783384-2ecb9200-3c1e-11ea-86ac-f4a064a5ce74.png)

**Comment by adavison007** [comment]
@tonesto7 Hi. I truly believe looking at how other thermostats work in home kit, the one item that really needs fixing in the code is that when you go to "AUTO" Mode, it 100% should have one temp (not a range) and that temp should be the default set temp in the thermostat settings... this is what Tado native does and also others. please let me know, with this fix I can live with the rest :) Your support would be appreciate.

**Comment by tonesto7** [comment]
I’m trying to tell you that’s not how it’s supposed to work. 
I have native HomeKit thermostat and auto works by having 2 set-points.  
I also wrote the Nest Integration for ST which has been active for the 4 years so I understand thermostats very well.  
The TADO setup is definitely not the standard model for thermostats. 

I’m order to support them the way you want I’m going to need to add something to the app to allow you to define them as a Tado and build completely separate logic for them in the plugin. 
I’m going to be honest it’s going to be awhile before I can get to that.

**Comment by tonesto7** [comment]
![71A62232-2013-404D-9799-DEA3A42E7E30](https://user-images.githubusercontent.com/1835933/73137035-2dd1a080-4022-11ea-9c4a-a81abef0fbf9.png)
This is my Lennox iComfort thermostat which has direct HomeKit support

**Comment by jdebardi** [comment]
Have a thermostat that allows a range is nice, but I've never seen one that does until now (it's obviously only been made possible since digital thermostats have come about).
For 50+ years thermostats have had a single point you set them to and based on that it would be odd that Apple have neglected to make it possible to have a simple single temp thermostat (and as Tado have managed it) it must be possible.

**Comment by tonesto7** [comment]
I truly think you should invest in the internet bridge and add native HomeKit to your tado.

**Comment by tonesto7** [comment]
@jdebardi There is a single setpoint.  The UI just shows you the range.  
I’m not going to rewrite the whole logic to address a purely cosmetic issue. 
I’m truly trying to understand why this is such a big issue.  Is your thermostat not working under my plugin?

**Comment by jdebardi** [comment]
Tbh I’m not using your plugin for Tado, I’m using native. I’m only adding as I have experience with Tado which seemed relevant here.

I don’t understand how you set the single set point if the UI gives you a range though!?
If a range is presented then the thermostat must have to understand a range input as well.

**Comment by JJJ** [comment]
## Auto
![4231655D-94E8-4122-9323-A874F1746723](https://user-images.githubusercontent.com/88951/73138104-8b66ec80-4024-11ea-92bc-2e18d8ccad71.png)

# Cool & Heat
![F37D9CE7-C323-4BE5-B160-FF6F9DB4EEC7](https://user-images.githubusercontent.com/88951/73138105-8b66ec80-4024-11ea-8119-4bc5c1dba4f9.png)

This is with an Ecobee using native HomeKit.

Even when I’ve used Nest and Homebridge, this is how it looked and worked. I’d expect nothing different.

I don’t like the range personally, because it seems to work opposite of what my needs are depending on the season (minimum heat, maximum cool) but this is just how it is.

**Comment by tonesto7** [comment]
@jdebardi to change the temp when it shows a range just grab one end of the dial and drag it

**Comment by jdebardi** [comment]
I get how to use the UI.

But the physical thermostat on the wall that controls the boiler understands only a single set point. So let’s say it’s aiming for 20 degrees.

If HomeKit is presented with this single value, what range does it display?

And if shall we say the range in HomeKit is 18-22 degrees, if I drag that out to 18-24, what does this pass to the Thermostat (via ST of course)? It is incapable of receiving a range.

**Comment by tonesto7** [comment]
The problem here lies in the fact that the st device handler implements an auto mode capability in a way that’s not based on the standard thermostat capabilities defined under st. 
Auto mode requires the ability to set a heat and cool setpoint. 

I get what your saying but you need to see it from a standards perspective.  The Tado configuration does not follow the standard.  

The only thing I can think to do in the shorterm is to add an input to the smartapp to define as a heat only thermostat and remove auto feature altogether

**Comment by jdebardi** [comment]
Ah! So now it makes sense!

Definitely add heat only option! That will completely solve it. Outside of North America not many people have heat and cool systems, just heat!

**Comment by tonesto7** [comment]
@jdebardi that's good to know.  
I will work on it when I can.  I’m traveling for work this week so maybe at night I will have some time to work from the Hotel

**Comment by adavison007** [comment]
Thanks @tonesto7 I agree in Europe nobody has both system of heat and cool, just heat… maybe in the settings for auto give the option of Auto Heat only or Auto heat and cool….

For auto with heat only, then make Auto set Smart things to “End Manual” that will then set the heating back to the standard set temp, then normal heat mode would be for changing the standard set heat and put it back into manual in Smartthings



Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 27 Jan 2020, at 14:41, tonesto7 <notifications@github.com> wrote:

@jdebardi <https://github.com/jdebardi> that's good to know.
I will work on it when I can. I’m traveling for work this week so maybe at night I will have some time to work from the Hotel

**Comment by JJJ** [comment]
Most thermostats automatically adjust their internal configurations based on how they are wired to the system.

When they are in 3-wire/heat-only mode, cooling/auto are not available as options inside their native applications or on the thermostats themselves.

My Nest worked that way, and my Ecobee does as well. If you unplug the air-conditioner wire, they both will detect it and you’ll be unable to choose cool/auto.

You’ll only have heat/off modes.

I’m unsure if part of the HomeKit/SmartThings spec provides a way to poll for mode changes. If it does, that’d be my suggestion as a way to try and automate this.

**Comment by adavison007** [comment]
Fo tado, heat happens when you manually change the heat for the set time, then if you turn off “manual Mode” it automatically goes back to the settings in the thermostat. This is Manual off in Tado, manual off in Smart things and auto in HomeKit (turns manual off)

Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 27 Jan 2020, at 15:52, John James Jacoby <notifications@github.com> wrote:

Most thermostats automatically adjust their internal configurations based on how they are wired to the system.

When they are in 3-wire/heat-only mode, cooling/auto are not available as options inside their native applications or on the thermostats themselves.

My Nest worked that way, and my Ecobee does as well. If you unplug the air-conditioner wire, they both will detect it and you’ll be unable to choose cool/auto.

You’ll only have heat/off modes.

I’m unsure if part of the HomeKit/SmartThings spec provides a way to poll for mode changes. If it does, that’d be my suggestion as a way to try and automate this.

**Comment by adavison007** [comment]
Any news ? Thanks in advance

Adam Davison
adavison@me.com
07748 761448

Sent from my iPhone

> On 27 Jan 2020, at 16:21, Adam Davison <adavison@me.com> wrote:
> 

﻿Fo tado, heat happens when you manually change the heat for the set time, then if you turn off “manual Mode” it automatically goes back to the settings in the thermostat. This is Manual off in Tado, manual off in Smart things and auto in HomeKit (turns manual off)

Adam Davison
adavison@me.com
01276 63145
07748 761448

On 27 Jan 2020, at 15:52, John James Jacoby <notifications@github.com> wrote:

Most thermostats automatically adjust their internal configurations based on how they are wired to the system.

When they are in 3-wire/heat-only mode, cooling/auto are not available as options inside their native applications or on the thermostats themselves.

My Nest worked that way, and my Ecobee does as well. If you unplug the air-conditioner wire, they both will detect it and you’ll be unable to choose cool/auto.

You’ll only have heat/off modes.

I’m unsure if part of the HomeKit/SmartThings spec provides a way to poll for mode changes. If it does, that’d be my suggestion as a way to try and automate this.

**Comment by adavison007** [comment]
@tonesto7 Did you get any time to have a play?

**Comment by tonesto7** [comment]
Nope... I've been traveling for work all week.  I don't think I'll have time until next week.

**Comment by adavison007** [comment]
Thanks for the update, I know that feeling 👍

Adam Davison
adavison@me.com
07748 761448

Sent from my iPhone

> On 1 Feb 2020, at 16:52, tonesto7 <notifications@github.com> wrote:
> 

﻿
Nope... I've been traveling for work all week. I don't think I'll have time until next week.
