### ISSUE TITLE
(BUG) temperature readings incorrect for sensors

### ISSUE THREAD

**Issue by jarvismeier** [tonesto7/homebridge-smartthings-v2#8]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The SmartApp and Device Handler are using the latest code available.
-  [ x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 64
-  Mobile App Version(Not required):
-  SmartApp Version:2.0.1
-  Device Handler Version:
-  Homebridge Version:0.4.50
-  NodeJS Version:10.9.0

## Expected Behavior
**Tell us what you think should be happening**
Contact and motion sensors in Home app should have the same temp as what is listed in smartthings

## Current Behavior
**What happens instead of the expected behavior?**
Temperature settings are showing in home app as much lower than smartthings.  Ie the actual reading is 22 degrees Celsius but in home app it’s showing as -5.5 degrees 

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Open any sensors 
2. Observe the listed temperature.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

I use temperature readings in conjunction with automations of some HomeKit only devices such as iHome outdoor plug to operate space heaters in case my furnace stops working when I’m away.
---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
Thanks for reporting this I will try to track this down

**Comment by jarvismeier** [comment]
I think you might need a config value to indicate F or C.  I’m running in Celsius.  I see it grabbing the correct value from smartthings but i think it’s putting it in as a Fahrenheit value.  In the example above 22F would convert to -5.5 Celsius.

**Comment by tonesto7** [comment]
I just pushed out some fixes.  It may take a moment for all your temps to be corrected but just make sure to select the correct unit in the smartapp.
