### ISSUE TITLE
(BUG) Strange notifications issue

### ISSUE THREAD

**Issue by ghost** [tonesto7/homebridge-smartthings-v2#81]
Hello. I have a Danalock Zigbee version connected and it shows up etc and works as expected in HomeKit. 
I have one issue, HomeKit notifications for the does not always arrive when I lock or unlock the door manually for example. For other door/window sensors this works fine. If I checked the home app I can see that the lock has changed status but I get no notification about it. Any ideas?

**Comment by tonesto7** [comment]
Are you positive that the notifications are enabled for the lock under the home app

**Comment by ghost** [comment]
Yes, I have also tried to remove and add the lock again etc but it's the same. I will try the zwave version of the lock in a couple of days and see if theres any difference because the lock also does not update the locked/unlocked status in the smartthings app when lock/unlock manually. This only happens after i have rebooted the hub once. I will report back in a couple of days. Thanks for the response

**Comment by jdebardi** [comment]
I am having the exact same thing with my Yale Conexis locks.
As you say, if you are in the Home app you see the status change real-time though so ST is obviously sending HomeKit the change of state, so I think it’s an Apple notification bug.
My Wife also does get all notifications, it’s only my phone that does not which adds more fuel to the Apple up assumption.
I’ve tried enabling/disabling notifications etc etc.
I’m still on the v1 version of this plugin so it’s not something that’s been added either.

**Comment by laskatj** [comment]
I’m having a similar issue with lock notifications for my kwikset 910. Logs show status Updates are being received by the plug-in, lock status updates in real time however no notifications are received. Randomly I will get one notification at times. Notifications are set up for the lock correctly in the home app. I see this issues marked as done but I don’t see any code change referenced?

**Comment by davidwhicker** [comment]
Sorry to hijack the thread. I have a Yale lock and want to try this plugin out. Is the unlock immediate if I use it in an automation? Ie when door unlocks then turn off alarm? @jdebardi

**Comment by jdebardi** [comment]
> Sorry to hijack the thread. I have a Yale lock and want to try this plugin out. Is the unlock immediate if I use it in an automation? Ie when door unlocks then turn off alarm? @jdebardi

Hi

Yes; it’s instant.
