### ISSUE TITLE
(BUG) {Homebridge v2 smart app shows 2x in new ST app only} 

### ISSUE THREAD

**Issue by shayfunk** [tonesto7/homebridge-smartthings-v2#83]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The SmartApp and Device Handler are using the latest code available.
-  [ x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?:49 so far
-  Mobile App Version(Not required):latest
-  SmartApp Version: smartthings v2
-  Device Handler Version:idk
-  Homebridge Version:3.18
-  NodeJS Version:idk

## Expected Behavior
**Tell us what you think should be happening**
Homebridge v2 (HB2) should show up once on SmartApps tab of new ST (connect) app? or I should not pay attention to it And only worry about classic. Just happened to be in app and notice.
## Current Behavior
**What happens instead of the expected behavior?**

Homebridge v2 (HB2) should show up twice on SmartApps tab of new ST (connect) app.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. installed per steps
2. had config issue 
3. fixed it 
4. thought things were fine and work fine (have logs that I used to find my issue and saved then after too) 
## Context
**How has this issue affected you? What are you trying to accomplish? concerned about making it worse because I want to go back into ST classic and add more of my devices like sensors, harmony activities as switches and a few other things.

---
Please include a copy of any relevant log output to assist in tracking down the bug Is there a way to attach I’m missing or is this a cut & paste situation? Sorry, I’m new to this.

**Comment by JJJ** [comment]
Not seeing this personally.

![37FED848-DC9D-4C05-840A-4D80983F957F](https://user-images.githubusercontent.com/88951/72912897-edacae00-3d01-11ea-8001-cec60dde3085.png)

Delete one of them (or both of them) and try again?

**Comment by shayfunk** [comment]
No, the app_id and access_token match one of the duplicate instances in the ST Connect app. I see my devices there and nothing in the classic app where I set it up. Also, I'm on ver 0.4.50 of homebridge and 2.2.2 of smart app (error above). I see two instances in both apps. When I was comparing initially I was in marketplace instead of the smart apps tab under automation. So I do in fact need to delete one. Thanks JJJ! I'm closing this. 

![AD435102-86A9-43CE-8A5F-77D72A65B136](https://user-images.githubusercontent.com/55553580/72950364-c8935c00-3d50-11ea-8494-c5339b647f78.jpeg)
