### ISSUE TITLE
‘Snippet’ of config.json

### ISSUE THREAD

**Issue by JGrahamK** [tonesto7/homebridge-smartthings-v2#85]
In the read me file, part 3.3, it directs that the config.json must be updated.  I got the update info from the app and edited it into a file, but I inadvertently overwrote the config.json with only the updated snippet portion because I’m new at this and didn’t immediately realize it was a snippet rather than the entire new config.json file.  Two questions:  1) What’s the best way to get the complete original config.json file so I can edit & upload that instead of the snippet? 2) To make sure I replace it, what directory would hold the incorrect/partial config.json?  I’m using a raspberry pi.  
Thanks

**Comment by tonesto7** [comment]
Here is the sample config:
https://github.com/nfarina/homebridge/blob/master/config-sample.json

**Comment by JGrahamK** [comment]
Perfect - thanks
