### ISSUE TITLE
(BUG) 'local' mode not working on Raspberry Pi

### ISSUE THREAD

**Issue by mrkarlos** [tonesto7/homebridge-smartthings-v2#86]
The local mode doesn't work on my Raspberry Pi device. Running a nest shows that port 8000 is on tcp6 and not on tcp4. Is this expected?

```
pi@kitchen:/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util $ sudo netstat -nltp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:49494           0.0.0.0:*               LISTEN      604/gmediarender
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      712/sshd        
tcp6       0      0 :::32947                :::*                    LISTEN      1313/homebridge 
tcp6       0      0 :::51827                :::*                    LISTEN      1313/homebridge 
tcp6       0      0 :::49494                :::*                    LISTEN      604/gmediarender
tcp6       0      0 :::22                   :::*                    LISTEN      712/sshd        
tcp6       0      0 :::40761                :::*                    LISTEN      1313/homebridge 
tcp6       0      0 :::40763                :::*                    LISTEN      1313/homebridge 
tcp6       0      0 :::37979                :::*                    LISTEN      1313/homebridge 
tcp6       0      0 :::43291                :::*                    LISTEN      1313/homebridge 
tcp6       0      0 :::42079                :::*                    LISTEN      1313/homebridge 
tcp6       0      0 :::8000                 :::*                    LISTEN      1313/homebridge 
tcp6       0      0 :::36877                :::*                    LISTEN      1313/homebridge
```

**Comment by scoobaspeaz** [comment]
Its how its configured and running on mine and I am not experiencing any issues:

root@homebridge:~# netstat -tulp |grep 8000
tcp6       0      0 [::]:8000               [::]:*                  LISTEN      26810/homebridge

**Comment by tonesto7** [comment]
@scoobaspeaz Aren’t you having issues with device events being relayed from ST to Homebridge?

**Comment by tonesto7** [comment]
> The local mode doesn't work on my Raspberry Pi device. Running a nest shows that port 8000 is on tcp6 and not on tcp4. Is this expected?
> 
> ```
> pi@kitchen:/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util $ sudo netstat -nltp
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> tcp        0      0 0.0.0.0:49494           0.0.0.0:*               LISTEN      604/gmediarender
> tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      712/sshd        
> tcp6       0      0 :::32947                :::*                    LISTEN      1313/homebridge 
> tcp6       0      0 :::51827                :::*                    LISTEN      1313/homebridge 
> tcp6       0      0 :::49494                :::*                    LISTEN      604/gmediarender
> tcp6       0      0 :::22                   :::*                    LISTEN      712/sshd        
> tcp6       0      0 :::40761                :::*                    LISTEN      1313/homebridge 
> tcp6       0      0 :::40763                :::*                    LISTEN      1313/homebridge 
> tcp6       0      0 :::37979                :::*                    LISTEN      1313/homebridge 
> tcp6       0      0 :::43291                :::*                    LISTEN      1313/homebridge 
> tcp6       0      0 :::42079                :::*                    LISTEN      1313/homebridge 
> tcp6       0      0 :::8000                 :::*                    LISTEN      1313/homebridge 
> tcp6       0      0 :::36877                :::*                    LISTEN      1313/homebridge
> ```

I don’t think this will work with the ST hub sending   Events. It’s targeting the IPV4 addess of the Homebridge host.  

I think I need to investigate this more

**Comment by scoobaspeaz** [comment]
> @scoobaspeaz Aren’t you having issues with device events being relayed from ST to Homebridge?

Nope im not having that issue at all. Granted im using only two lightbulbs so not sure how much of a real test that is. But it works.

The thing I was babbling about in my bug was something im not even sure is ST plugin related. It was homebridge simply randomly not working with HomeKit but then coming back within 5 mins or so. 

Only other thing was asking in that bug was wanting to know more info on how the SmartApp, ST, and homebridge all work together in a workflow for security reasons.

**Comment by tonesto7** [comment]
@mrkarlos I have some fixes in place for this.  I hope to have a release out by Tuesday

**Comment by tonesto7** [comment]
So I've been looking into this and I can't get ST LanEvents to work reliably anymore.  Something changed on the ST side and I can't figure out how to make it work correctly.
In the upcoming version, I've removed the local commands option as it really doesn't improve performance much.
