### ISSUE TITLE
Security System showing up in Homekit

### ISSUE THREAD

**Issue by skbeez** [tonesto7/homebridge-smartthings-v2#88]
I have successfully updated my Smartthings plugin to v2 but now I am seeing an additional security system in my HomeKit app. I already have a Ring security system so how do I hide the Smartthings security system?

**Comment by skbeez** [comment]
Argh... I goofed up. The option I was looking for was the Smart Home Monitor switch in the Smartapp configuration. Once I did that and generated/pasted the new credentials into my config.json the security system disappeared. I will close this bug.

**Comment by muzzymate** [comment]
Thank you. I'm in progress now of switching from Wink to Smartthings and could not figure out how to get rid of the Smartthings security system in the Home app. That did the trick!
