### ISSUE TITLE
[Feature Request] Support for Garage Door

### ISSUE THREAD

**Issue by matt-oneill** [tonesto7/homebridge-smartthings-v2#89]
I have a meross smart garage door opener set up in ST which I would like to be able to control in Home with this plugin.

Currently I have this set up with IFTTT Webhooks to open/close the door but it does not know The state of the door if it is opened manually as the ST app does.

**Comment by tonesto7** [comment]
If the device shows up under ST with the garage door capability then it will work.  I don't really want to try and support custom device capabilities if I don't have too.

**Comment by matt-oneill** [comment]
It is a garage door in ST but it isn’t available to select in the Homebridge v2 SmartApp under device types or all other devices, am I missing something?

**Comment by tonesto7** [comment]
@matt-oneill 
Can you go into the SmartApp and tap on Device Data Viewer and select the Garage Door device and post the output generated here.

**Comment by matt-oneill** [comment]
@tonesto7 
It does not appear in sensors, switches or other devices in device data viewer.

**Comment by yaggayoyo** [comment]
+1

**Comment by turnepf** [comment]
After updating homebridge and the smart app I moved my garage doors to the new garage door option in the SmartThings app (latest app on iOS). They disappeared both from home bridge and from HomeKit. I changed them back to the "others" section and they came back. They work fine for me this way (with all features) but figured I'd let you all know. Thanks for all of the hard work!
