### ISSUE TITLE
(BUG) SHM changes on ST side do not reflect on Homebridge side

### ISSUE THREAD

**Issue by badamonis** [tonesto7/homebridge-smartthings-v2#9]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The SmartApp and Device Handler are using the latest code available.
-  [X] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 1
-  Mobile App Version(Not required):
-  SmartApp Version: 2.0.1
-  Device Handler Version: N/A
-  Homebridge Version: 2.0.1
-  NodeJS Version: 10.17.0

## Expected Behavior
**Tell us what you think should be happening**
When SHM state is changed in ST Classic, the device on the Homebridge side should update to reflect change. When SHM state is changed in Home app, it should be updated in ST Classic

## Current Behavior
**What happens instead of the expected behavior?**
Changes to Smart Home Monitor state do not reflect on the Homebridge/Homekit side. Changes are visible in ST Classic when made from the Home app

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

**ST Classic > Homebridge (NOT WORKING)**

1. Change SHM to Armed Stay in ST Classic app
2. View log in IDE
`2:57:43 PM: debug Sending LOCATION Event (alarm system status | ALARMSYSTEMSTATUS: stay) to Homebridge at (x.x.x.x:xxxx)` 
3. No event is created in Homebridge
4. Change is not reflected in iOS Home app

**Homebridge > ST Classic (WORKING)**

1. Change SHM to Armed Stay in Home app
2. View event in Homebridge log
`[12/8/2019, 3:00:48 PM][SmartThings-v2]NOTICE: Sending Device Command: stay | Value: Nothing | DeviceID: (alarmSystemStatus_...deviceID) | SendToLocalHub: (true)`
3. Event is logged in IDE
`3:00:49 PM: debug Sending LOCATION Event (alarm system status | ALARMSYSTEMSTATUS: stay) to Homebridge at (x.x.x.x:xxxx)`
4. Verify change in ST Classic app

## Context
**How has this issue affected you? What are you trying to accomplish?
I am not able to control set SHM device on Homebridge/Homekit side to effect change in ST.

**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
i am able to duplicate this but just need to sort out why.  This may take me a week to get addressed

**Comment by tonesto7** [comment]
I just pushed out a new plugin which should solve this.

**Comment by OnlyOnly0613** [comment]
I assume this is related but it does not work both ways. HB to SMH [or] SMH to HB
I am not using SmartThings Classic. I am using the new SmartThings app.
