### ISSUE TITLE
View Configuration Data for Homebridge

### ISSUE THREAD

**Issue by nimbleslick** [tonesto7/homebridge-smartthings-v2#90]
Homebridge Noob Here:

Please save me from this year's Darwin Award nominations and tell me why I cannot find the "View Configuration Data for Homebridge" anywhere in the Smartthings SmartApp - I am using the classic app, but I see no options, no menus, nothing that says View Configuration Data for Homebridge

Any help would be appreciated, thank you!

**Comment by tonesto7** [comment]
I might of forgotten to update the instructions.  

I renamed the input `Render the platform data for Homebridge config.json`

**Comment by nimbleslick** [comment]
Sorry I am specifically asking about where to find the App URL, App Token, and App ID for the configuration of the SmartApp. Thank you very much for your prompt attention! Awesome!

**Comment by nimbleslick** [comment]
![Screen Shot 2020-02-05 at 2 33 14 PM](https://user-images.githubusercontent.com/10222630/73885143-8542ee00-4824-11ea-9887-fa62a93a3db4.png)

**Comment by tonesto7** [comment]
Can you post this question in the ST Community I need to keep these issues cleaned up?
