### ISSUE TITLE
Two GE In-Wall Smart Dimmer Switches - one dimmable, other just a switch

### ISSUE THREAD

**Issue by muzzymate** [tonesto7/homebridge-smartthings-v2#91]
I have two GE In-Wall Smart Dimmer light switches. One is a decora/rocker-style while the other is a toggle-style dimmer. For some reason I have not been able to determine, the rocker-style is showing up in the Home app as a simple on/off switch. The toggle-style shows as a dimmer. 

I first reviewed the "Device Data Viewer" for both, but doing a side-by-side comparison, there does not appear to be a difference, with the capabilities and commands listed being identical. I do see where the output is displaying on as a light while the other is a switch. I've tried deleting the cachedaccessories file and restarting the instance, but the output and does not correct the issue. 

Working / Toggle

———
{
    "name": "Entry Way Lighting",
    "basename": "GE In-Wall Smart Dimmer",
    "deviceid": "dd788c06-e45c-40e6-954c-45143484f378",
    "status": "ONLINE",
    "manufacturer": "Jasco Products",
    "model": "Dimmer Switch",
    "deviceNetworkId": "07",
    "lastActivity": "2020-02-08T02:04:31+0000",
    "capabilities": [
        "Actuator",
        "Health Check",
        "Indicator",
        "Light",
        "Refresh",
        "Sensor",
        "Switch",
        "Switch Level"
    ],
    "commands": [
        "indicatorNever",
        "indicatorWhenOff",
        "indicatorWhenOn",
        "off",
        "on",
        "ping",
        "refresh",
        "setLevel"
    ],
    "customflags": [
        
    ],
    "attributes": {
        "DeviceWatch-DeviceStatus": null,
        "DeviceWatch-Enroll": null,
        "checkInterval": 1920,
        "healthStatus": null,
        "indicatorStatus": "when on",
        "level": 20,
        "switch": "on"
    },
    "eventHistory": [
        "Sat Feb 08 02:04:26 UTC 2020 | [null] | (on)",
        "Sat Feb 08 02:04:26 UTC 2020 | [null] | (setLevel)",
        "Sat Feb 08 02:04:24 UTC 2020 | [null] | (setLevel)",
        "Sat Feb 08 02:04:24 UTC 2020 | [null] | (on)",
        "Sat Feb 08 02:04:23 UTC 2020 | [level] | (20)",
        "Sat Feb 08 02:04:22 UTC 2020 | [level] | (52)",
        "Sat Feb 08 02:04:22 UTC 2020 | [null] | (setLevel)",
        "Sat Feb 08 02:04:21 UTC 2020 | [null] | (setLevel)",
        "Sat Feb 08 02:04:21 UTC 2020 | [null] | (on)",
        "Sat Feb 08 02:04:17 UTC 2020 | [null] | (on)",
        "Sat Feb 08 02:04:17 UTC 2020 | [null] | (setLevel)",
        "Sat Feb 08 02:04:16 UTC 2020 | [null] | (on)",
        "Sat Feb 08 02:04:16 UTC 2020 | [null] | (setLevel)",
        "Sat Feb 08 02:00:48 UTC 2020 | [switch] | (on)",
        "Sat Feb 08 02:00:41 UTC 2020 | [switch] | (off)",
        "Sat Feb 08 01:59:52 UTC 2020 | [switch] | (on)",
        "Sat Feb 08 01:59:47 UTC 2020 | [switch] | (off)",
        "Sat Feb 08 01:53:24 UTC 2020 | [level] | (74)",
        "Sat Feb 08 01:53:20 UTC 2020 | [switch] | (on)",
        "Sat Feb 08 01:53:10 UTC 2020 | [switch] | (off)"
   ]
}

Non-dimmable Dimmer / Rocker

{
    "name": "Dining Room",
    "basename": "GE In-Wall Smart Dimmer",
    "deviceid": "d684e9be-25ec-4a65-a73b-b35fcdc3d3be",
    "status": "ONLINE",
    "manufacturer": "Jasco Products",
    "model": "Dimmer Switch",
    "deviceNetworkId": "06",
    "lastActivity": "2020-02-08T02:07:09+0000",
    "capabilities": [
        "Actuator",
        "Health Check",
        "Indicator",
        "Light",
        "Refresh",
        "Sensor",
        "Switch",
        "Switch Level"
    ],
    "commands": [
        "indicatorNever",
        "indicatorWhenOff",
        "indicatorWhenOn",
        "off",
        "on",
        "ping",
        "refresh",
        "setLevel"
    ],
    "customflags": [
        
    ],
    "attributes": {
        "DeviceWatch-DeviceStatus": null,
        "DeviceWatch-Enroll": null,
        "checkInterval": 1920,
        "healthStatus": null,
        "indicatorStatus": "when on",
        "level": 100,
        "switch": "off"
    },
    "eventHistory": [
        "Sat Feb 08 02:07:09 UTC 2020 | [switch] | (off)",
        "Sat Feb 08 02:07:03 UTC 2020 | [null] | (off)",
        "Sat Feb 08 02:06:54 UTC 2020 | [switch] | (on)",
        "Sat Feb 08 02:06:54 UTC 2020 | [level] | (100)",
        "Sat Feb 08 02:06:48 UTC 2020 | [null] | (on)",
        "Sat Feb 08 01:47:31 UTC 2020 | [switch] | (off)",
        "Sat Feb 08 01:17:43 UTC 2020 | [level] | (100)",
        "Sat Feb 08 01:17:38 UTC 2020 | [level] | (4)",
        "Sat Feb 08 01:17:37 UTC 2020 | [null] | (on)",
        "Sat Feb 08 01:17:33 UTC 2020 | [null] | (off)",
        "Sat Feb 08 00:56:41 UTC 2020 | [switch] | (on)",
        "Sat Feb 08 00:56:41 UTC 2020 | [level] | (100)",
        "Sat Feb 08 00:49:12 UTC 2020 | [level] | (100)",
        "Sat Feb 08 00:49:03 UTC 2020 | [level] | (37)",
        "Sat Feb 08 00:48:56 UTC 2020 | [level] | (100)",
        "Sat Feb 08 00:48:53 UTC 2020 | [switch] | (on)",
        "Sat Feb 08 00:48:53 UTC 2020 | [level] | (64)",
        "Sat Feb 08 00:48:49 UTC 2020 | [switch] | (off)",
        "Sat Feb 08 00:48:42 UTC 2020 | [level] | (100)",
        "Sat Feb 08 00:48:20 UTC 2020 | [level] | (15)"
    ]
}

The debug output is showing one as being a light while the other is a switch.

Working 

> [2/7/2020, 9:22:52 pm] [SmartThings-v2] DEBUG: Loading Existing Device (Entry Way Lighting) | (dd788c06-e45c-40e6-954c-45143484f378)
> [2/7/2020, 9:22:52 pm] [SmartThings-v2] **DEBUG: Entry Way Lighting ' | ' 'light'**
> [2/7/2020, 9:22:52 pm] [SmartThings-v2] GOOD: [CHARACTERISTIC (function() {
>   Characteristic.call(this, 'On', '00000025-0000-1000-8000-0026BB765291');
>   this.setProps({
>     format: Characteristic.Formats.BOOL,
>     perms: [Characteristic.Perms.READ, Characteristic.Perms.WRITE, Characteristic.Perms.NOTIFY]
>   });
>   this.value = this.getDefaultValue();
> }) GET] switch (Entry Way Lighting) | LastUpdate: (Fri Feb 07 2020 21:22:52 GMT-0500 (Eastern Standard Time)) | Value: (true)
> [2/7/2020, 9:22:52 pm] [SmartThings-v2] GOOD: [CHARACTERISTIC (function() {
>   Characteristic.call(this, 'Brightness', '00000008-0000-1000-8000-0026BB765291');
>   this.setProps({
>     format: Characteristic.Formats.INT,
>     unit: Characteristic.Units.PERCENTAGE,
>     maxValue: 100,
>     minValue: 0,
>     minStep: 1,
>     perms: [Characteristic.Perms.READ, Characteristic.Perms.WRITE, Characteristic.Perms.NOTIFY]
>   });
>   this.value = this.getDefaultValue();
> }) GET] level (Entry Way Lighting) | LastUpdate: (Fri Feb 07 2020 21:22:52 GMT-0500 (Eastern Standard Time)) | Value: (20)

Non-dimmable Dimmer - 

> [2/7/2020, 9:22:52 pm] [SmartThings-v2] DEBUG: Loading Existing Device (Dining Room) | (d684e9be-25ec-4a65-a73b-b35fcdc3d3be)
> [2/7/2020, 9:22:52 pm] [SmartThings-v2] **DEBUG: Dining Room ' | ' 'switch_device'**
> [2/7/2020, 9:22:52 pm] [SmartThings-v2] GOOD: [CHARACTERISTIC (function() {
>   Characteristic.call(this, 'On', '00000025-0000-1000-8000-0026BB765291');
>   this.setProps({
>     format: Characteristic.Formats.BOOL,
>     perms: [Characteristic.Perms.READ, Characteristic.Perms.WRITE, Characteristic.Perms.NOTIFY]
>   });
>   this.value = this.getDefaultValue();
> }) GET] switch (Dining Room) | LastUpdate: (Fri Feb 07 2020 21:22:52 GMT-0500 (Eastern Standard Time)) | Value: (false)

**Comment by tonesto7** [comment]
Yea that is weird.

I think you've exposed a bug. 
Add both of them under the Define Device Types > Lights and they should both be added as dimmable  devices.

**Comment by TejasAntani** [comment]
I've noticed a similar issue.  Jasco Dimmer Switch appears as a standard switch.

**Comment by muzzymate** [comment]
I went into Define Device Types > Lights and selected them both. That bypasses whatever oddity was occurring and now both are appearing as dimmers.  Thank you @tonesto7!

**Comment by tonesto7** [comment]
The more I think about this I finally remember why it's like this. 
It's difficult for me to assume whether something is a Dimmer just because it has a Switch and Switch Level capability

**Comment by TejasAntani** [comment]
Am I required to update every device in the SmartThings smart app and cut and past the api key etc every time I make a change to single device configuration?

**Comment by muzzymate** [comment]
Ok, I'll close it then if the design was on purpose. It was strange to have one a dimmer and one a switch of basically identical hardware. Either way, glad that you've built in an easy way to override default behavior.

@TejasAntani - You should not have to update the API key in config.json file. Making changes in the Smartthings app SmartApp section should take place quickly, but I end up restarting the instance for good measure.
