### ISSUE TITLE
(BUG) {Thermostats not showing up at all in homekit} 

### ISSUE THREAD

**Issue by whoopn** [tonesto7/homebridge-smartthings-v2#92]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The SmartApp and Device Handler are using the latest code available.
-  [X] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

TO MY KNOWLEDGE: You only have a smartapp right?  My device handlers are normal smartthings handlers.
---
## About Your Setup
-  How many devices are detected?: 60, these are the only two not detected
-  Mobile App Version(Not required):
-  SmartApp Version: 2.2.2
-  Device Handler Version: Its the CT100 Thermostat, its support is built in to SmartThings
-  Homebridge Version: 0.4.50
-  NodeJS Version: 12.13.0 

## Expected Behavior
**Tell us what you think should be happening**
Well I don't know, should the thermo show up?  Is there a compatibility issue?

## Current Behavior
**What happens instead of the expected behavior?**
It doesn't show up in the homekit app nor in homebridge

---
Please include a copy of any relevant log output to assist in tracking down the bug
I'm currently having a hard time getting the logs to work properly, is there other information I can provide in the meantime?

**Comment by tonesto7** [comment]
I'm not sure how to help with this... 
Can you please open the smart app and goto the Device Data Viewer > Select the device > View Data > Share the full output here?

**Comment by whoopn** [comment]
Thank you for helping me look into this. The output is below. 

{
    "name": "Upstairs Thermostat",
    "basename": "Radio Thermostat CT101",
    "deviceid": "d6af2c77-b6eb-49aa-8aef-47d51c8c9886",
    "status": "ONLINE",
    "manufacturer": "Radio Thermostat Company of America (RTC)",
    "model": "CT100 Thermostat",
    "deviceNetworkId": "0D",
    "lastActivity": "2020-02-13T04:11:37+0000",
    "capabilities": [
        "Actuator",
        "Battery",
        "Health Check",
        "Refresh",
        "Relative Humidity Measurement",
        "Sensor",
        "Temperature Measurement",
        "Thermostat"
    ],
    "commands": [
        "auto",
        "cool",
        "emergencyHeat",
        "fanAuto",
        "fanCirculate",
        "fanOn",
        "heat",
        "lowerCoolSetpoint",
        "lowerHeatingSetpoint",
        "off",
        "ping",
        "poll",
        "raiseCoolSetpoint",
        "raiseHeatingSetpoint",
        "refresh",
        "setCoolingSetpoint",
        "setHeatingSetpoint",
        "setSchedule",
        "setThermostatFanMode",
        "setThermostatMode",
        "switchFanMode",
        "switchMode"
    ],
    "customflags": [

    ],
    "attributes": {
        "DeviceWatch-DeviceStatus": null,
        "DeviceWatch-Enroll": null,
        "battery": 100,
        "checkInterval": 1920,
        "coolingSetpoint": 79,
        "coolingSetpointRange": null,
        "healthStatus": null,
        "heatingSetpoint": 72,
        "heatingSetpointRange": null,
        "humidity": 20,
        "schedule": null,
        "supportedThermostatFanModes": "[auto, on]",
        "supportedThermostatModes": "[heat, cool, off, auto]",
        "temperature": 72,
        "thermostatFanMode": "auto",
        "thermostatFanState": "idle",
        "thermostatMode": "auto",
        "thermostatOperatingState": "idle",
        "thermostatSetpoint": 72,
        "thermostatSetpointRange": null
    },
    "eventHistory": [
        "Thu Feb 13 04:11:37 UTC 2020 | [temperature] | (72 F)",
        "Thu Feb 13 03:58:15 UTC 2020 | [temperature] | (71 F)",
        "Thu Feb 13 03:44:32 UTC 2020 | [thermostatOperatingState] | (idle)",
        "Thu Feb 13 03:12:27 UTC 2020 | [temperature] | (72 F)",
        "Thu Feb 13 03:01:00 UTC 2020 | [temperature] | (71 F)",
        "Thu Feb 13 02:45:31 UTC 2020 | [thermostatSetpoint] | (72 F)",
        "Thu Feb 13 02:27:15 UTC 2020 | [temperature] | (70 F)",
        "Thu Feb 13 02:27:15 UTC 2020 | [thermostatOperatingState] | (heating)",
        "Thu Feb 13 02:14:01 UTC 2020 | [temperature] | (69 F)",
        "Thu Feb 13 01:33:53 UTC 2020 | [coolingSetpoint] | (79 F)",
        "Thu Feb 13 01:26:26 UTC 2020 | [temperature] | (70 F)",
        "Thu Feb 13 01:13:19 UTC 2020 | [temperature] | (69 F)",
        "Thu Feb 13 00:55:21 UTC 2020 | [thermostatOperatingState] | (idle)",
        "Thu Feb 13 00:23:15 UTC 2020 | [thermostatOperatingState] | (heating)",
        "Wed Feb 12 23:51:28 UTC 2020 | [thermostatOperatingState] | (idle)",
        "Wed Feb 12 23:19:26 UTC 2020 | [temperature] | (70 F)",
        "Wed Feb 12 23:08:38 UTC 2020 | [temperature] | (69 F)",
        "Wed Feb 12 22:46:18 UTC 2020 | [thermostatSetpoint] | (70 F)",
        "Wed Feb 12 22:46:17 UTC 2020 | [thermostatOperatingState] | (heating)",
        "Wed Feb 12 22:46:16 UTC 2020 | [heatingSetpoint] | (70 F)"
    ]
}

**Comment by whoopn** [comment]
I figured it out!

You cannot add these devices as tstat devices. It wasn’t even counting them in the total device counts in the smartapp. I added them as “other devices” and all is well now.

Thank you
