### ISSUE TITLE
Can't Get Passed Step 1

### ISSUE THREAD

**Issue by rjarosh** [tonesto7/homebridge-smartthings-v2#94]
I can't seem to get this working from the first steps on my raspberry pi. I type:

sudo npm install -g --unsafe-perm homebridge-config-ui-x

And I get this:

`(node:32586) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN engine homebridge-config-ui-x@4.10.1: wanted: {"node":">=8.15.1","homebridge":">=0.4.22"} (current: {"node":"8.11.1","npm":"1.4.21"})
npm WARN package.json base64-arraybuffer@0.1.5 No license field.
npm WARN package.json component-bind@1.0.0 No license field.
npm WARN package.json component-inherit@0.0.3 No license field.
npm WARN package.json has-binary2@1.0.3 No repository field.
npm WARN package.json callsite@1.0.0 No repository field.
npm WARN package.json callsite@1.0.0 No license field.
npm WARN package.json indexof@0.0.1 No repository field.
npm WARN package.json indexof@0.0.1 No license field.
npm WARN package.json json-schema@0.2.3 No license field.
npm WARN package.json object-component@0.0.3 No repository field.
npm WARN package.json object-component@0.0.3 No license field.
npm WARN package.json punycode@2.1.1 punycode is also the name of a node core module.
npm WARN package.json string_decoder@1.1.1 string_decoder is also the name of a node core module.
npm WARN package.json to-array@0.1.4 No license field.
npm WARN package.json xmlhttprequest-ssl@1.5.5 No license field.
npm WARN package.json better-assert@1.0.2 No license field.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.19.42-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge-config-ui-x"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0`

**Comment by tonesto7** [comment]
Please don't post this here I can't support the install of Config-UI-x.  
If you are having issues with the smartthings plugin directly, by all means, please reach out.
