### ISSUE TITLE
Door/Window Sensor Showing Not Active in Home App

### ISSUE THREAD

**Issue by kevinjonsutton** [tonesto7/homebridge-smartthings-v2#96]
Since moving over to v2 of the SmartApp, I have noticed that for all of my door and window sensors (SmartThings Multipurpose Sensors) it shows "Status Active...No" in the status section of the home app. This is causing an issue in the Eve app when my devices are brought over. I didn't have this issue in the original version of the SmartApp. I looked around but couldn't find a way to change this to yes or enable the device to be active as it must be tied to the code for the app. Is there a way to change this in the next update to show the device being active or remove this all together so these devices show correctly in the Eve app and can be automated? Thanks in advance!

![IMG_0125](https://user-images.githubusercontent.com/45573456/74991284-633b9500-53fa-11ea-8913-562969d5125c.PNG)
![IMG_0126](https://user-images.githubusercontent.com/45573456/74991355-90884300-53fa-11ea-995a-ca1024a3c699.PNG)
![IMG_0127](https://user-images.githubusercontent.com/45573456/74991360-95e58d80-53fa-11ea-90a5-3cf25c88f611.PNG)

**Comment by tonesto7** [comment]
Does the device show online under SmartThings?  That’s what drives the active value.

**Comment by kevinjonsutton** [comment]
Yes it does, that's the strange thing. I have a buddy who has the same setup and checked his home app and it shows the same thing.

![IMG_0129](https://user-images.githubusercontent.com/45573456/74998641-1feb2180-540e-11ea-9d12-b0d3bc93c02b.PNG)

![IMG_0128](https://user-images.githubusercontent.com/45573456/74998645-211c4e80-540e-11ea-9fc1-bafe724512ba.PNG)

**Comment by tonesto7** [comment]
Thanks for reporting this.  I'm working on a fix right now...

**Comment by tonesto7** [comment]
Ok... I've tracked down and resolved the issue.  I will be deploying this sometime tomorrow.
