### ISSUE TITLE
(BUG) {2.3.0 Smart App won't save or publish in IDE} 

### ISSUE THREAD

**Issue by adavison007** [tonesto7/homebridge-smartthings-v2#97]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The SmartApp and Device Handler are using the latest code available.
-  [x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
On latest version for homebrdige and can't save 2.3.0 in ST IDE

Error = 

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script_app_metadata_24dc8845_54c1_460b_bd7d_f0f9b46219e4: 979: unexpected token: [ @ line 979, column 16.
items?.["Thermostat"] = 1
^

1 error

## Expected Behavior
**it should be working**

## Current Behavior
**Can;t save new ST Smart APP Code**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by mmdfhome** [comment]
I'm facing the same issue with the upgrade. I "fixed" it by removing the "?." from line 979 and 982. Once those were removed, I was able to publish in IDE.

**Comment by tonesto7** [comment]
i published a fix for these...
