### ISSUE TITLE
(BUG) Can't access 2.30 SmartApp in ST.

### ISSUE THREAD

**Issue by realdannys** [tonesto7/homebridge-smartthings-v2#98]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  X That _OAuth_ is Enabled for the SmartApp under the IDE.
-  X The SmartApp and Device Handler are using the latest code available.
-  X That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 20
-  SmartApp Version: 2.30
-  Homebridge Version: 2.30
-  NodeJS Version: 12.14.1

## Current Behavior
In the Classic ST app I cannot open the published Homebridge v2 SmartApp any longer. Pressing on it just display the spinning loading icon and then nothing happens. This has only happened since the update to 2.30. 

## Expected Behavior
Should load into the screen of the app to select which devices you want available to Homebridge

## Steps to Reproduce (for bugs)

Try to open SmartApp in ST Classic.

Unfortunately I cannot get live logging to show anything when I try to open the app and I obviously can't get into the app anymore to enable debugging.

**Comment by adavison007** [comment]
I had the same issue, it's because they is a coding issue in the smart app to do with thermostats, so it's not running... I guess you did update from repo... if you cut and paste the code in, it does not allow you to save due to the code error, i have opened a bug on this.

**Comment by tonesto7** [comment]
I'm working on it right now... sorry for the trouble 😦

**Comment by tonesto7** [comment]
Ok... it's fixed and released.
