### ISSUE TITLE
(BUG) {smart app shows old homebridge plugin code alert} 

### ISSUE THREAD

**Issue by adavison007** [tonesto7/homebridge-smartthings-v2#99]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The SmartApp and Device Handler are using the latest code available.
-  [x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---

## Expected Behavior
The Smart app shows i need to update my homebirdge plugin, I have done this and also rebooted homebridge and also saved on the smart app, it still shows in the smart app that my homebridge plugin is old when it isn't

Also, I still get a rate in my thermostat after these new plugins, I thought it was going to be removed and when you clicked auto it would set the default temprature?

![IMG_1255](https://user-images.githubusercontent.com/47482260/75053395-1ffc2780-54c9-11ea-9386-883f19cce0e6.png)

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
Once the plugin is updated this will change

**Comment by tonesto7** [comment]
Make sure to install the latest versions of both.  (v2.3.1)

**Comment by adavison007** [comment]
> Once the plugin is updated this will change

Hi @tonesto7 the plugin was updated a few hours ago :) and the smart app isn't recognising that it was updated
<img width="609" alt="Untitled 2" src="https://user-images.githubusercontent.com/47482260/75053745-b6c8e400-54c9-11ea-9ce6-d0586b9ec2ce.png">

**Comment by tonesto7** [comment]
There was a bug in v2.3.0 with reporting in.  There is now a v2.3.1 of both the smart app and plugin.
I was tired and trying to get the new version released and forgot to validate before releasing it. 

https://www.npmjs.com/package/homebridge-smartthings-v2

**Comment by adavison007** [comment]
> Make sure to install the latest versions of both. (v2.3.1)

@tonesto7 No 2.3.1 for homebridge on npm ? 

<img width="609" alt="Screenshot 2020-02-21 at 16 50 44" src="https://user-images.githubusercontent.com/47482260/75054204-8f264b80-54ca-11ea-9425-867fd1deb970.png">

**Comment by tonesto7** [comment]
![image](https://user-images.githubusercontent.com/1835933/75055268-b49f5f00-54a2-11ea-9c5a-d4b2bc8e394b.png)

**Comment by tonesto7** [comment]
Maybe it hasn't replicated yet.

**Comment by adavison007** [comment]
> Maybe it hasn't replicated yet.

@tonesto, thanks, NPM now shows it but hoobs does not show an update.. did it in terminal instead, will give feedback shortly. thanks for your time with this.
